### ISSUE TITLE
[BUG]: 单间节点的clickhouse 在控制台创建表异常

### ISSUE THREAD

**Issue by Chenkeyi43** [clickvisual/clickvisual#1006]
**Describe the bug**
控制台建表失败

**ClickVisual Running Environment**
Please provide the following information:

- ClickVisual version:
clickvisual-v1.0.0-rc2
- ClickVisual.LOG:
- 
{"data":{"code":1,"msg":"storage create failed: error sql is: CREATE TABLE IF NOT EXISTS `log`.`nglog_local` on cluster ''\n(\n`stream` String,\n`time` String,\n`kubernetes` String,\n_time_second_ DateTime,\n_time_nanosecond_ DateTime64(9),\n_raw_log_ String CODEC(ZSTD(1)),\n_key String CODEC(ZSTD(1)),\n`_headersname` Array(String),\n`_headersvalue` Array(String),\nINDEX idx_raw_log _raw_log_ TYPE tokenbf_v1(30720, 2, 0) GRANULARITY 1\n)\nENGINE = ReplicatedMergeTree('/clickhouse/tables/log.nglog_local/{shard}', '{replica}')\nPARTITION BY toYYYYMMDD(_time_second_)\nORDER BY _time_second_\nTTL toDateTime(_time_second_) + INTERVAL 1 DAY\nSETTINGS index_granularity = 8192;\n: code: 139, message: No macro 'shard' in config while processing substitutions in '/clickhouse/tables/log.nglog_local/{shard}' at '36' or macro is not supported here","data":"storage create failed: error sql is: CREATE TABLE IF NOT EXISTS `log`.`nglog_local` on cluster ''\n(\n`stream` String,\n`time` String,\n`kubernetes` String,\n_time_second_ DateTime,\n_time_nanosecond_ DateTime64(9),\n_raw_log_ String CODEC(ZSTD(1)),\n_key String CODEC(ZSTD(1)),\n`_headersname` Array(String),\n`_headersvalue` Array(String),\nINDEX idx_raw_log _raw_log_ TYPE tokenbf_v1(30720, 2, 0) GRANULARITY 1\n)\nENGINE = ReplicatedMergeTree('/clickhouse/tables/log.nglog_local/{shard}', '{replica}')\nPARTITION BY toYYYYMMDD(_time_second_)\nORDER BY _time_second_\nTTL toDateTime(_time_second_) + INTERVAL 1 DAY\nSETTINGS index_granularity = 8192;\n: code: 139, message: No macro 'shard' in config while processing substitutions in '/clickhouse/tables/log.nglog_local/{shard}' at '36' or macro is not supported here"}}

后端节点截图：
<img width="1471" alt="image" src="https://github.com/clickvisual/clickvisual/assets/64025526/decb7878-a5b8-49d6-841e-9fe4b91a8e7d">

**Comment by kl7sn** [comment]
原因是识别出来是单节点副本，但是有集群配置（parallel_replicas）

**Comment by donglihe** [comment]
遇到相同情况，有啥修复方法没？

**Comment by kl7sn** [comment]
可以使用最新的 rc 版本，这个地方进行了修复。

**Comment by Chenkeyi43** [comment]
> 遇到相同情况，有啥修复方法没？

我是通过修改数据库的字段的，有个 CV_instance 的表里面的一个字段 是表示集群还是单机的
