### ISSUE TITLE
[BUG]:service "prometheus" depends on undefined service prom2click: invalid compose project

### ISSUE THREAD

**Issue by cplinux** [clickvisual/clickvisual#1008]
**Describe the bug**
service "prometheus" depends on undefined service prom2click: invalid compose project

docker-compose文件中没有叫prom2click的service

**ClickVisual Running Environment**
Please provide the following information:

- ClickVisual version:

- ClickVisual.LOG:

**Comment by kl7sn** [comment]
最新版本中进行了修复
