### ISSUE TITLE
[BUG]: 拥有日志权限，但无权执行自定义SQL查询

### ISSUE THREAD

**Issue by hasylu** [clickvisual/clickvisual#1009]
Clickvisual版本：clickvisual-v1.0.0-rc1-linux-amd64.tar
问题描述：用户设置了日志的全部权限，日志查询正常可用，但选自定义SQL窗口，提示未知错误，如图所示
![244661062-f48e6c46-9cef-441f-b827-390aa21d4ccd](https://github.com/clickvisual/clickvisual/assets/3271307/54b190d7-7006-4995-bdfd-cb79836471ee)

curl信息如下：
curl 'http://xx.xx.xx.xx:19001/api/v1/instances/2/complete?query=SELECT%0A++*%0AFROM%0A++%60database_name%60.%60table_name%60%0AWHERE%0A++timestamp+%3E%3D+toDateTime64(1686303167,+3)%0A++AND+timestamp+%3C+toDateTime64(1686304067,+3)%0A++AND+(1+%3D+%271%27)%0AORDER+BY%0A++timestamp+DESC%0ALIMIT%0A++10%0AOFFSET%0A++0' \
  -X 'POST' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36' \
  -H 'Origin: http://xx.xx.xx.xx:19001' \
  -H 'Referer: http://xx.xx.xx.xx:19001/query?end=1686304067&index=2&logState=0&page=1&queryType=statisticalTable&size=10&start=1686303167&tab=relative&tid=53' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7,es;q=0.6,ja;q=0.5' \
  -H 'Cookie: clickvisual_session=MTY4NjMwMzkxNnxOd3dBTkZsUldGSkhSMUZaV0ZsRVR6VlNOVUpTU0RKT1FVaFdWamRRVWxGRFV6UkRVelpZVlZoWldEWlFVVkpKU1ZwUE5VOVpUVkU9fIKGv3wz4YpAOBZO13QcuyuXD8cAI9aweDp-K2M13ZyJ' \
  --compressed \
  --insecure
![网络请求](https://github.com/clickvisual/clickvisual/assets/3271307/543d3b03-062e-4267-bdc2-d9d0ab4b1fc2)

响应信息如下：
![响应](https://github.com/clickvisual/clickvisual/assets/3271307/7bb40e77-7fb8-4287-8b9b-0457f06cf494)

**Comment by kl7sn** [comment]
这里验证的是用户对 ClickHouse 实例分配的读权限。

**Comment by hasylu** [comment]
实例管理的配置
![微信截图_20230612110525](https://github.com/clickvisual/clickvisual/assets/3271307/7aae81f2-006d-4db2-9bab-a130aa422ef8)

角色管理的配置
![微信截图_20230612110551](https://github.com/clickvisual/clickvisual/assets/3271307/998ed7b8-4fed-4acb-8796-5efb0672f290)

帮看看还需要添加其他哪些权限

**Comment by kl7sn** [comment]
授权作用域，需要对实例授权。

**Comment by hasylu** [comment]
> 授权作用域，需要对实例授权。

授权作用域好像没有实例相关的选项，是不是版本有关
![授权作用域](https://github.com/clickvisual/clickvisual/assets/3271307/cd6adc84-42b7-456f-b42e-7acf721426ba)

**Comment by kl7sn** [comment]
目前这里只能选择全部，因为没有开发SQL识别，可以执行任意语句
有相关的开发计划，识别出具体的 table 并且限定只进行读操作，还在开发中
https://github.com/clickvisual/clickvisual/issues/975

**Comment by hasylu** [comment]
> 目前这里只能选择全部，因为没有开发SQL识别，可以执行任意语句
> 
> 有相关的开发计划，识别出具体的 table 并且限定只进行读操作，还在开发中 #975

收到
