### ISSUE TITLE
[BUG]:开启匿名访问，重启后，页面显示白屏

### ISSUE THREAD

**Issue by BruceWayneVsSuperMan** [clickvisual/clickvisual#1010]
**Describe the bug**
修改default.toml以下内容重启后白屏
[auth.anonymous]
# enable anonymous access
enabled = true

只有顶部用户栏为anonymous，点击数据库结构升级报错：错误：permission verification failed。
只能重新关闭匿名登录功能

**ClickVisual Running Environment**
Please provide the following information:

- ClickVisual version:
最新版本 v1.0.0-rc2

- ClickVisual.LOG:
`"lv":"warn","ts":1686560028,"msg":"ReadAllPermissionInstance","uid":999999,"step":"DatabaseViewIsPermission","iid":1,"tid":9,"subResource":"base"}
{"lv":"error","ts":1686560028,"msg":"pms","step":"Assemble2CasbinStr","error":"empty string is not permitted in parameters"}
{"lv":"error","ts":1686560028,"msg":"pms","step":"Assemble2CasbinStr","error":"empty string is not permitted in parameters"}
{"lv":"warn","ts":1686560028,"msg":"ReadAllPermissionInstance","uid":999999,"step":"DatabaseViewIsPermission","iid":1,"tid":8,"subResource":"alarm"}
{"lv":"warn","ts":1686560028,"msg":"ReadAllPermissionInstance","uid":999999,"step":"DatabaseViewIsPermission","iid":1,"tid":9,"subResource":"alarm"}
{"lv":"error","ts":1686560028,"msg":"pms","step":"Assemble2CasbinStr","error":"empty string is not permitted in parameters"}
{"lv":"error","ts":1686560028,"msg":"pms","step":"Assemble2CasbinStr","error":"empty string is not permitted in parameters"}
{"lv":"warn","ts":1686560028,"msg":"ReadAllPermissionInstance","uid":999999,"step":"DatabaseViewIsPermission","iid":1,"tid":8,"subResource":"bigdata"}
{"lv":"warn","ts":1686560028,"msg":"ReadAllPermissionInstance","uid":999999,"step":"DatabaseViewIsPermission","iid":1,"tid":9,"subResource":"bigdata"}
{"lv":"error","ts":1686560188,"msg":"bizError","value":"permission verification failed","error":"需要root超级管理员权限. ","tid":"7dc6bf15f3a716deea292e383a8881a4"}`

页面展示如图：
![image](https://github.com/clickvisual/clickvisual/assets/17560384/43ce6bdb-7002-44ae-8471-79f202a82485)

**Comment by kl7sn** [comment]
用管理员设置匿名用户的可见范围，例如对某个实例设置对任意用户可见。
