### ISSUE TITLE
bug: RFC3339 时间格式带时区保存报错

### ISSUE THREAD

**Issue by yluchao** [clickvisual/clickvisual#1018]
**Describe the bug**
创建日志表时，如果时间字段带上时区就会报错，我的日志如下
{
    "@timestamp": "2023-06-15T17:30:33.208+08:00",
    "content": "内容内容，日志内容",
    "level": "info",
    "rows": 1,
    "span": "7c9c251df0bd3717",
    "time": "4.60068ms",
    "trace": "0ee55c3d0d21240c2e21fd98b95fbe50"
}
保存后会提示
{"data":{"code":1,"msg":"storage create failed: code: 62, message: Syntax error: failed at position 141 ('@') (line 8, col 3): @timestamp String,\n  content String CODEC(ZSTD(1))\n)\nENGINE = Kafka SETTINGS kafka_broker_list = 'localhost:9002', \nkafka_topic_list = 'test. Expected one of: table property (column, index, constraint) declaration, INDEX, CONSTRAINT, PROJECTION, PRIMARY KEY, column declaration, identifier, token, ClosingRoundBracket","data":"storage create failed: code: 62, message: Syntax error: failed at position 141 ('@') (line 8, col 3): @timestamp String,\n  content String CODEC(ZSTD(1))\n)\nENGINE = Kafka SETTINGS kafka_broker_list = 'localhost:9002', \nkafka_topic_list = 'score_mall_go_qa_ne. Expected one of: table property (column, index, constraint) declaration, INDEX, CONSTRAINT, PROJECTION, PRIMARY KEY, column declaration, identifier, token, ClosingRoundBracket"}}
如果将时间格式改为：**2023-06-15T09:30:36.308Z**，不带时区的话就可以保存

**ClickVisual Running Environment**
Please provide the following information:

- ClickVisual version:

1.0.0-rc2

- ClickVisual.LOG:

**Comment by kl7sn** [comment]
https://github.com/clickvisual/clickvisual/pull/1116 进行了修复
