### ISSUE TITLE
bug:查询完折叠日志点击展开，页面崩溃

### ISSUE THREAD

**Issue by charles-liming** [clickvisual/clickvisual#1029]
<img width="859" alt="image" src="https://github.com/clickvisual/clickvisual/assets/34326414/af2c8cee-2299-47c6-8a54-fa573193bae6">

**Comment by charles-liming** [comment]
版本为0.4.6

**Comment by charles-liming** [comment]
![image](https://github.com/clickvisual/clickvisual/assets/34326414/bf54fc20-92c3-455b-b9c1-0f943a44edeb)
这条日志差不多有3MB大

**Comment by kl7sn** [comment]
崩溃报错是什么，方便提供下吗，可能是展开之后解析问题。

**Comment by charles-liming** [comment]
<img width="1086" alt="image" src="https://github.com/clickvisual/clickvisual/assets/34326414/77f317a4-f12e-48ed-822a-659e4e0ec6d5">

**Comment by charles-liming** [comment]
大概意思就是，我们单条日志比较大，500KB的大小就可以复现这个异常

**Comment by Huhui-coder** [comment]
这个问题会进行修复吗？场景还是很容易就能够进行复现的，遇到的概率比较大。

**Comment by wuzhihui1123** [comment]
我这也有同样的问题，当单条日志量比较大的时候，浏览器就会失去响应

**Comment by kl7sn** [comment]
感谢反馈，这边会尽快优化。

**Comment by wuzhihui1123** [comment]
这个问题复现和修复了吗？ @kl7sn

**Comment by kl7sn** [comment]
优化比较麻烦，之前的功能涉及嵌套解析。
