### ISSUE TITLE
question: Table metrics.samples doesn't exist。

### ISSUE THREAD

**Issue by ChainsDW** [clickvisual/clickvisual#1032]
情况：
平台上显示，metrics.samles检测正常，但是我注意到这个表是生成在实例的metrics里的，实例里有这个表和库，但是在配置文件的prom2click.cfgs的clickhouseDSN 里配置的dns是我本地的另一个clickhouse，我如果这个配置是写实例的地址是没问题的，所以，其实这里配置到底是什么情况？如果多个实例又是怎么运行的？我应该怎么配置
报错：
query: running sql: SELECT COUNT() AS CNT, (intDiv(toUInt32(ts), 10) * 10) * 1000 as t, name, tags, quantile(0.750000)(val) as value FROM metrics.samples WHERE date >= toDate(1691156353) AND ts >= toDateTime(1691156353) AND ts <= toDateTime(1691242753) AND arrayExists(x -> x IN ('alarmId=2' ), tags) = 1 AND arrayExists(x -> x IN ('filterId=3' ), tags) = 1 AND arrayExists(x -> x IN ('uuid=91686281-4d87-4077-a38d-70ed5a2faa92' ), tags) = 1 AND  name='clickvisual_alert_metrics'  GROUP BY t, name, tags ORDER BY t
Error: query failed: SELECT COUNT() AS CNT, (intDiv(toUInt32(ts), 10) * 10) * 1000 as t, name, tags, quantile(0.750000)(val) as value FROM metrics.samples WHERE date >= toDate(1691156353) AND ts >= toDateTime(1691156353) AND ts <= toDateTime(1691242753) AND arrayExists(x -> x IN ('alarmId=2' ), tags) = 1 AND arrayExists(x -> x IN ('filterId=3' ), tags) = 1 AND arrayExists(x -> x IN ('uuid=91686281-4d87-4077-a38d-70ed5a2faa92' ), tags) = 1 AND  name='clickvisual_alert_metrics'  GROUP BY t, name, tags ORDER BY tError: query error: code: 60, message: Table metrics.samples doesn't exist

**Comment by kl7sn** [comment]
metrics.samples 存储监控指标数据的表
prom2click.cfgs 的 clickhouseDSN 配置的是 prometheus 读取的 clickhouse 地址

如何配置取决于你想让 prometheus 读取哪个 clickhouse 的 metrics.samples

**Comment by ChainsDW** [comment]
明白了，如果多个实例配置多个prom2click.cfgs就可以了是吗
