### ISSUE TITLE
k8s内部署clickvisual，多pod无法登陆。

### ISSUE THREAD

**Issue by mingqibee** [clickvisual/clickvisual#1047]
k8s内部署clickvisual，多pod无法登陆。

现象：2个pod情况下，点击登录10次有1-2次登录成功，登录失败的时候就是页面闪一下(类似浏览器刷新)，还是停留在登录页面。
![image](https://github.com/clickvisual/clickvisual/assets/38835550/2c5fe1e3-6509-4bc9-acb5-c6f77142ecb6)

相关配置文件：
```
    [app]
    isMultiCopy = true  # multi-copy mode: Redis must be configured, otherwise the service cannot start
    secretKey = "secretKey"
    rootURL = "https://domain.com"
    baseURL = "/api/admin/login/"
    permissionFile = './config/resource.yaml'
    serveFromSubPath = false

    [redis]
    debug = true
    addr = "clickvisual-redis:6379"
    writeTimeout = "3s"
    password = ""
```
登录时两个pod日志：
![image](https://github.com/clickvisual/clickvisual/assets/38835550/bc90c796-230e-4df2-ad51-dc641ee55d9d)

redis内key信息：
![image](https://github.com/clickvisual/clickvisual/assets/38835550/dd81c1ca-fd6c-43c3-8cee-3576145269c8)

浏览器console报错：
![image](https://github.com/clickvisual/clickvisual/assets/38835550/34c2367e-8c3c-4811-a37e-cdf119e2618e)

浏览器network接口无报错，返回都是200：
![image](https://github.com/clickvisual/clickvisual/assets/38835550/fedea717-d6e3-4e82-93c7-fd2a4fca6574)

**Comment by kl7sn** [comment]
https://clickvisual.net/zh/clickvisual/04appauth/clickvisual-auth.html

用户认证设置的部分要改成 redis
