### ISSUE TITLE
feat: 日志聚类

### ISSUE THREAD

**Issue by PalanQu** [clickvisual/clickvisual#1051]
我用golang实现了[在线的日志聚类算法](https://github.com/PalanQu/LoggingDrain3)，clickvisual是否需要此功能？如果需要的话一起看一下如何集成？

**Comment by kl7sn** [comment]
这个算法肯定是有帮助的，我这边先 fork 了，最近其他事情比较多，之后找时间看下集成方式

**Comment by PalanQu** [comment]
@kl7sn 如果有什么帮助随时@我，我可以帮助一起搞

**Comment by askuy** [comment]
> 在线的日志聚类算法

这个是解决什么问题的，用在什么场景呢

**Comment by PalanQu** [comment]
@askuy https://help.aliyun.com/zh/sls/user-guide/logreduce，类似于sls的日志聚类，用在看日志、基于日志的故障定位

**Comment by askuy** [comment]
这个是单独对数据处理吧。并不是作用于clickhouse，或者操作文件日志

> @askuy [sls链接](https://help.aliyun.com/zh/sls/user-guide/logreduce)，类似于sls的日志聚类 场景
> 
> * 看日志
> * 基于日志的故障定位场景

**Comment by PalanQu** [comment]
@askuy 对，单纯是一个算法，想问问是否可以加在clickvisual做一个功能而已
