### ISSUE TITLE
question: 按照官网的流程 使用 docker-compose 无法启动 Error: unknown command "server" for "clickvisual"

### ISSUE THREAD

**Issue by zhailibao2013** [clickvisual/clickvisual#1055]
Before asking a question, please first consider:

- Searching [existing discussions](https://github.com/clickvisual/clickvisual/discussions/)
- Searching [existing issues](https://github.com/clickvisual/clickvisual/issues/)
- Searching Google

-------

提问之前，建议先在 ClickVisual 社区寻找答案。

- 查看 [存在的 discussions](https://github.com/clickvisual/clickvisual/discussions/)
- 查看 [存在的 issues](https://github.com/clickvisual/clickvisual/issues/)
- 查看 [中文文档](https://clickvisual.net/clickvisual/01quickstart/qa.html)
- 查看 Google

如果仍然无法找到答案，我们建议您在[discussions](https://github.com/clickvisual/clickvisual/discussions/)进行提问。

![clickvisual](https://github.com/clickvisual/clickvisual/assets/7806943/2b1d3d28-909f-48c9-9ff8-483e054fac4d)

**Comment by ihatake** [comment]
请问最后解决了吗？我也遇到的同样的问题

**Comment by kl7sn** [comment]
再更新下最新的 master 分支代码试试

**Comment by dingjunxin** [comment]
最新代码还是不行

**Comment by kl7sn** [comment]
可以确认下镜像是否更新了，或者直接制定具体版本。
<img width="404" alt="image" src="https://github.com/clickvisual/clickvisual/assets/2037801/721641b9-ebf1-42fe-b8bb-86b64df208bb">
