### ISSUE TITLE
question:按照官网的流程 使用 docker-compose 无法启动 Error: unknown command "install" for "clickvisual"

### ISSUE THREAD

**Issue by HAVENT81** [clickvisual/clickvisual#1066]
Hi kl7sn，我根据提示下载的 v1.0.0-rc7 基于 amd64 的二进制安装包，解压后使用里面的 docker-compose 进行安装，clickvisual-v100-rc7-mock-1 无法启动报错 Error: unknown command "install" for "clickvisual"
![图片](https://github.com/clickvisual/clickvisual/assets/7400502/0de27473-a32d-4f1b-a382-8e68b3bffcbe)
![图片](https://github.com/clickvisual/clickvisual/assets/7400502/cc575508-38b5-4f38-bcb2-8a4c9db0f30b)
![图片](https://github.com/clickvisual/clickvisual/assets/7400502/917ead2a-8ca4-4f48-b79a-72894da77d28)
![图片](https://github.com/clickvisual/clickvisual/assets/7400502/40af5d60-a4ef-49b7-bb24-188cf15a1cfd)

**Comment by kl7sn** [comment]
mock 的效果是协助用户添加一个本地实例，可以忽略这个报错，该功能后续移除了，手动增加实例即可。

**Comment by HAVENT81** [comment]
clickvisual 容器状态是 running，但是 19001 端口的网页无法访问，下面是错误日志，/install/init 页面也是无法访问

![图片](https://github.com/clickvisual/clickvisual/assets/7400502/6c97ae45-06ce-4608-974a-f70067c98db6)

**Comment by HAVENT81** [comment]
mysql 库中只会自动生成一张 cv_pms_casbin_rule 的空表

**Comment by HAVENT81** [comment]
已解决，出现上述问题的原因是执行 `docker-compose up` 之前需要将 github 代码库中的 /data/all-in-one/ 目录拷贝到 ......../clickvisual-v1.0.0-rc7/data/all-in-one/ 目录。然后执行 `docker-compose up` 即可完成初始化。最后补充一下，我这边的访问地址不知道为什么后台系统的端口变成 18001 了，前面一个劲的尝试 19001 永远无法访问
