### ISSUE TITLE
feat:登录home界面的几个JS文件太大，打开页面太慢

### ISSUE THREAD

**Issue by manfrid** [clickvisual/clickvisual#1084]
登录页面的几个大JS文件有点大，加载时间太长了，每次都从服务器下载，能否加cache-control， 加载一次后，下次直接304

**Comment by kl7sn** [comment]
目前已增加
<img width="503" alt="image" src="https://github.com/clickvisual/clickvisual/assets/2037801/aebeb304-8300-4830-b88a-c818c0acb105">

**Comment by kl7sn** [comment]
支持版本为 https://github.com/clickvisual/clickvisual/releases/tag/v1.0.0-rc12

**Comment by askuy** [comment]
增加 gzip https://github.com/clickvisual/clickvisual/pull/1114
