### ISSUE TITLE
日志一栏希望可以配置别名而不是数据库中真实的database和table_name

### ISSUE THREAD

**Issue by forkTemi** [clickvisual/clickvisual#1091]
日志库名称希望可以配置别名显示而不是数据库中真实的database和table_name

**Comment by kl7sn** [comment]
暂时使用这个方式显示
<img width="180" alt="image" src="https://github.com/clickvisual/clickvisual/assets/2037801/47543b6a-bc59-4d2e-ba6d-fab801f9fb77">

**Comment by kl7sn** [comment]
支持版本为 https://github.com/clickvisual/clickvisual/releases/tag/v1.0.0-rc12
