### ISSUE TITLE
bug:报警链接打开报错

### ISSUE THREAD

**Issue by merseyalma** [clickvisual/clickvisual#1097]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.

**ClickVisual Running Environment**
Please provide the following information:

- ClickVisual version:

clickvisual-1.0.0-rc11

- ClickVisual.LOG:

配置的报警规则

![image](https://github.com/clickvisual/clickvisual/assets/10740987/2904be37-d76e-49d0-a9da-2904a87f0f78)

收到报警后，点击报警链接，跳转到 http://ip:19001/share/?end=1700198883&index=2&kw=SELECT%0A%20%20count%281%29%20AS%20val%2C%0A%20%20status%0AFROM%0A%20%20naccess%0AWHERE%0A%20%20stat_date%20%3D%20today%28%29%0A%20%20AND%20status%20%3D%20%27200%27%0A%20%0AGROUP%20BY%0A%20%20status%0AORDER%20BY%0A%20%20val%20DESC&logState=NaN&mode=0&page=1&queryType=rawLog&size=10&start=1700198758&tab=custom&tid=1

报错

{"data":{"code":1,"msg":"SELECT * FROM `default`.`naccess` WHERE time_local >= toDateTime64(1700198758, 3) AND time_local < toDateTime64(1700198883, 3) AND (SELECT\n  count(1) AS val,\n  status\nFROM\n  naccess\nWHERE\n  stat_date = today()\n  AND status = '200'\n \nGROUP BY\n  status\nORDER BY\n  val DESC) ORDER BY time_local DESC LIMIT 10 OFFSET 0: code: 43, message: Illegal type (Tuple(UInt64, String)) of 3 argument of function and: While processing (time_local >= toDateTime64(1700198758, 3)) AND (time_local < toDateTime64(1700198883, 3)) AND __getScalar('13359105264446300049_16948636661821004205')","data":"SELECT * FROM `default`.`naccess` WHERE time_local >= toDateTime64(1700198758, 3) AND time_local < toDateTime64(1700198883, 3) AND (SELECT\n  count(1) AS val,\n  status\nFROM\n  naccess\nWHERE\n  stat_date = today()\n  AND status = '200'\n \nGROUP BY\n  status\nORDER BY\n  val DESC) ORDER BY time_local DESC LIMIT 10 OFFSET 0: code: 43, message: Illegal type (Tuple(UInt64, String)) of 3 argument of function and: While processing (time_local >= toDateTime64(1700198758, 3)) AND (time_local < toDateTime64(1700198883, 3)) AND __getScalar('13359105264446300049_16948636661821004205')"}}

**Comment by kl7sn** [comment]
提供下告警目标数据库的结构，我这边本地构造下复现问题后解决。

**Comment by merseyalma** [comment]
> 提供下告警目标数据库的结构，我这边本地构造下复现问题后解决。

```
CREATE TABLE default.naccess
(
    `country` String,
    `upstream_uri` String,
    `upstream_addr` String,
    `uri` String,
    `request_method` String,
    `http_host` String,
    `http_user_agent` String,
    `stat_hour` String,
    `manufacturer` String,
    `remote_user` String,
    `upstream_status` String,
    `request_time` Float32,
    `province` String,
    `browser` String,
    `model` String,
    `browser_version` String,
    `brand` String,
    `remote_addr` String,
    `stat_date` Date,
    `stat_min` String,
    `time_local` DateTime64(3),
    `http_version` String,
    `city` String,
    `body_sent_bytes` String,
    `http_referrer` String,
    `server_name` String,
    `upstream_response_time` String,
    `status` String,
    `application_code` String,
    `create_time` DateTime64(3) DEFAULT now()
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(stat_date)
ORDER BY time_local
SETTINGS index_granularity = 8192

```

**Comment by kl7sn** [comment]
在本次提交 https://github.com/clickvisual/clickvisual/pull/1115 进行了修复，之后会进行版本发布
