### ISSUE TITLE
question:k8s节点较多的时候，登陆能不能支持多节点，现在节点多的时候接口调用多了会退出

### ISSUE THREAD

**Issue by zhiqiu1995** [clickvisual/clickvisual#1099]
k8s节点较多的时候，登陆能不能支持多节点，现在节点多的时候接口调用多了会退出

-------

提问之前，建议先在 ClickVisual 社区寻找答案。

- 查看 [存在的 discussions](https://github.com/clickvisual/clickvisual/discussions/)
- 查看 [存在的 issues](https://github.com/clickvisual/clickvisual/issues/)
- 查看 [中文文档](https://clickvisual.net/clickvisual/01quickstart/qa.html)
- 查看 Google

如果仍然无法找到答案，我们建议您在[discussions](https://github.com/clickvisual/clickvisual/discussions/)进行提问。

**Comment by askuy** [comment]
https://clickvisual.net/zh/clickvisual/04appauth/clickvisual-auth.html#clickvisual-auth
默认是使用的memory session，所以多节点会存在问题。

如果是多节点，使用redis session mode换为redis，同时增加redis配置
