### ISSUE TITLE
question:使用查询ck的方式来做告警不会对ck本身稳定性造成影响吗？

### ISSUE THREAD

**Issue by lovejoy** [clickvisual/clickvisual#1142]
查看目前是使用定期查询ck的方式来做告警，如果一个ck集群支撑了多个业务，写入量本来就很大，以及加了多条策略的话，还用这样的方式会不会对ck本身稳定性有影响的，你们的写入&策略的量级和实践是怎么样的？

**Comment by kl7sn** [comment]
写数据的方式是通过物化实图实现，该功能是 clickhouse 提供的核心能力，有很高的可靠性；
prometheus 通过 remote_read 的方式读取数据，没有复杂的语句和计算不会有性能问题。
