### ISSUE TITLE
选择已有数据表时是否可以支持多选，很多表结构都是一样的，不需要每个都要重复操作一次

### ISSUE THREAD

**Issue by beyond688** [clickvisual/clickvisual#142]
![image](https://user-images.githubusercontent.com/39320802/162170790-fbcfec39-0dcf-4905-a021-100ad9802917.png)

**Comment by kl7sn** [comment]
了解，这个可以纳入开发流程。

**Comment by kl7sn** [comment]
@beyond688 多选功能已经上线了，可以体验下这个是否满足需求，有其他问题也可以继续提出来。

<img width="896" alt="image" src="https://user-images.githubusercontent.com/2037801/168721125-96cefdd2-7018-4770-baaf-16c7c4717564.png">
