### ISSUE TITLE
用户体验建议

### ISSUE THREAD

**Issue by qinjianping** [clickvisual/clickvisual#157]
![162861914-485c4301-a0d4-4086-8ce3-c1e7496673a1](https://user-images.githubusercontent.com/36214123/162882481-255c013f-d9e2-4e0e-bdb1-68a0913facf7.jpg)
![162861970-f7f1b3f1-2f36-495a-9dcc-bd720564dabe](https://user-images.githubusercontent.com/36214123/162882489-08b3c6b4-34f5-41cb-8ab6-d28ec3f33abd.jpg)
![162861994-db61ecd5-9db2-4430-8cba-cc5e271e9db9](https://user-images.githubusercontent.com/36214123/162882498-196604bf-3662-4591-aab9-02a030ec9067.jpg)
![162862013-26e28101-b65d-4e40-84f0-ff97be861a1b](https://user-images.githubusercontent.com/36214123/162882506-94c1f908-f9ee-4849-9e8d-dddb723f8a1d.jpg)

**Comment by kl7sn** [comment]
结合你这边提出的优化建议，下一步的开发计划包括
1. 数据表新增和更新增加描述字段，并进行展示
2. 切换数据库的界面调整为树状结构，并讲新增数据表操作移动到该界面中

**Comment by kl7sn** [comment]
@qinjianping 以上提出的大部分需求都进行了相关开发，其中核心的数据库和日志库之间的显示问题也进行了对应优化。
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/2037801/168721663-56f8e9f8-8c69-425b-bd77-c39c6a8abdd4.png">
