### ISSUE TITLE
【功能需求】建议增加自定义SQL

### ISSUE THREAD

**Issue by qinjianping** [clickvisual/clickvisual#158]
![162862054-2cdafa9c-3498-46a0-b5d1-9aff7fdeab69](https://user-images.githubusercontent.com/36214123/162882555-696a376c-d040-4f32-9c53-2de2b5f08792.jpg)

**Comment by kl7sn** [comment]
这个确实是需求点，目前我们这边的解决方式是通过数据库管理工具进行 SQL 语句操作完成建表，然后再接入 MOGO。
支持 SQL 语句是比较简单的，但是过程中考虑到校验、数据展示和交互优化等方面需要考虑比较多的东西，才能给出良好的使用体验，所以目前开发的优先级不高。
