### ISSUE TITLE
趋势图步长建议与图表展示

### ISSUE THREAD

**Issue by hjun881** [clickvisual/clickvisual#159]
* 优化 
   *  趋势图增加步长与点数的设置.  比如设置最小步长为1分钟最大点位为30，那么15分钟的数据就显示15个趋势点位(一分钟一个点位)，如果30分钟的数据就显示30个点位(一分钟一个点位),如果是1个小时的数据就显示最大30个点位(两分钟一个点位)

* 新功能
   * 增加以表的形式显示数据,并增加切换按钮用户可自行选择以列的形式展示数据或者以表的形式展示数据.

**Comment by kl7sn** [comment]
趋势图间隔规则调整，相关提交 https://github.com/shimohq/mogo/pull/160/files#diff-93d7168d791612e6c1cb2b39f9f324f034fc2a3925808c8a1b97cd1b92a56dbb
