### ISSUE TITLE
添加ck实例不支持http连接

### ISSUE THREAD

**Issue by zuihoudiandian** [clickvisual/clickvisual#164]
http://host:8123?username=default&password=xxx&read_timeout=10&write_timeout=20
![ddad706781f37e6a6fa1bef8e3fb894](https://user-images.githubusercontent.com/40695014/163114180-2b05e722-bf4d-4250-b569-67285e70995c.png)

**Comment by kl7sn** [comment]
目前使用的是 https://github.com/ClickHouse/clickhouse-go/tree/v1.5.1 进行连接，只支持 tcp 协议。

后续会进行 v2.0 版本的接入开发，采用以下方式进行连接创建

> clickhouse://username:password@host1:9000,host2:9000/database?dial_timeout=200ms&max_execution_time=60
