### ISSUE TITLE
请问用户权限怎么控制？

### ISSUE THREAD

**Issue by vincentob** [clickvisual/clickvisual#174]
您好，
   当前没看到有用户权限相关的配置，每个登录的人都能修改系统配置？

**Comment by sevennt** [comment]
近期我们会加上简单的权限控制功能

**Comment by kl7sn** [comment]
@vincentob 目前 v0.3.0 版本增加了 Casbin 权限管理模块，基于 clickhouse 实例，可自定义角色，支持权限级别为 database 或 table 的配置。
