### ISSUE TITLE
按照文档使用 docker-compose 在本地快速启动 Mogo demo表不存在问题

### ISSUE THREAD

**Issue by insomniasary** [clickvisual/clickvisual#188]
/mogo/api/internal/service/configure/lock.go:80 Error 1146: Table 'mocro.mogo_configuration' doesn't exist
 /mogo/api/pkg/model/db/cluster.go:118 Error 1146: Table 'mocro.mogo_cluster' doesn't exist
基本上表都不存在~

**Comment by kl7sn** [comment]
如果服务正常启动可以尝试访问访问 http://localhost:19001/install/init 进行数据库初始化。

**Comment by hzhijun** [comment]
没有表，貌似服务也启动不起来

**Comment by kl7sn** [comment]
@insomniasary 目前运行是否正常，如果没有其他问题，我们这边会关闭这个 issues。
