### ISSUE TITLE
直接使用docker-compose 快速启动失败

### ISSUE THREAD

**Issue by ArthurQiuys** [clickvisual/clickvisual#232]
panic:
    msg: Casbin NewEnforcer panic
    loc: /clickvisual/api/internal/service/permission/pmsplugin/pms.go:37
    error: open : no such file or directory
{"lv":"panic","ts":1652324394,"msg":"Casbin NewEnforcer panic","lname":"default.log","error":"open : no such file or directory","stack":"github.com/gotomicro/ego/core/elog.(*Component).Panic\n\t/go/pkg/mod/github.com/gotomicro/ego@v0.9.3-0.20220325064316-00eb36a764a1/core/elog/component.go:262\ngithub.com/gotomicro/ego/core/elog.Panic\n\t/go/pkg/mod/github.com/gotomicro/ego@v0.9.3-0.20220325064316-00eb36a764a1/core/elog/elog_api.go:42\ngithub.com/clickvisual/clickvisual/api/internal/service/permission/pmsplugin.Invoker\n\t/clickvisual/api/internal/service/permission/pmsplugin/pms.go:37\ngithub.com/clickvisual/clickvisual/api/internal/service/permission.InitManager\n\t/clickvisual/api/internal/service/permission/pms.go:23\ngithub.com/clickvisual/clickvisual/api/internal/service.Init\n\t/clickvisual/api/internal/service/init.go:34\ngithub.com/gotomicro/ego.runSerialFuncReturnError\n\t/go/pkg/mod/github.com/gotomicro/ego@v0.9.3-0.20220325064316-00eb36a764a1/ego_function.go:263\ngithub.com/gotomicro/ego.(*Ego).Invoker\n\t/go/pkg/mod/github.com/gotomicro/ego@v0.9.3-0.20220325064316-00eb36a764a1/ego.go:133\nmain.main\n\t/clickvisual/api/main.go:16\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255"}
panic: Casbin NewEnforcer panic

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00066e600, {0xc0004ae1c0, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.19.1/zapcore/entry.go:232 +0x446
go.uber.org/zap.(*Logger).Panic(0x2030b44, {0x2030b44, 0xc0004ae1c0}, {0xc0004ae1c0, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.19.1/logger.go:230 +0x59
github.com/gotomicro/ego/core/elog.(*Component).Panic(0xc0001ecd40, {0x2030b44, 0x18}, {0xc0004ae1c0, 0x1, 0x1})
	/go/pkg/mod/github.com/gotomicro/ego@v0.9.3-0.20220325064316-00eb36a764a1/core/elog/component.go:262 +0xd0
github.com/gotomicro/ego/core/elog.Panic(...)
	/go/pkg/mod/github.com/gotomicro/ego@v0.9.3-0.20220325064316-00eb36a764a1/core/elog/elog_api.go:42
github.com/clickvisual/clickvisual/api/internal/service/permission/pmsplugin.Invoker()
	/clickvisual/api/internal/service/permission/pmsplugin/pms.go:37 +0x365
github.com/clickvisual/clickvisual/api/internal/service/permission.InitManager(...)
	/clickvisual/api/internal/service/permission/pms.go:23
github.com/clickvisual/clickvisual/api/internal/service.Init()
	/clickvisual/api/internal/service/init.go:34 +0x1b9
github.com/gotomicro/ego.runSerialFuncReturnError({0xc0006ae640, 0x2, 0x3f448e8})
	/go/pkg/mod/github.com/gotomicro/ego@v0.9.3-0.20220325064316-00eb36a764a1/ego_function.go:263 +0x46
github.com/gotomicro/ego.(*Ego).Invoker(0xc0006ba3c0, {0xc0002f7f40, 0x2, 0x60})
	/go/pkg/mod/github.com/gotomicro/ego@v0.9.3-0.20220325064316-00eb36a764a1/ego.go:133 +0x165
main.main()
	/clickvisual/api/main.go:16 +0x65

没有看到相关的设置问题

**Comment by kl7sn** [comment]
感谢反馈问题，master 分支已修复，当前新增加的权限管理功能，docker 部分测试正在进行中。
