### ISSUE TITLE
docker-compose快速启动失败

### ISSUE THREAD

**Issue by ouyangzhongmin** [clickvisual/clickvisual#236]
![image](https://user-images.githubusercontent.com/7018141/168008852-2ddcd14a-9d75-474e-a4a5-a328c72400bd.png)

最新pull下来的, 系统：windows

**Comment by ouyangzhongmin** [comment]
再次pull已解决，但是新增日志库报错： 
![image](https://user-images.githubusercontent.com/7018141/168010002-327b28a5-90b3-4e88-9239-9f5e7f3d3bc6.png)

错误信息：{"data":{"code":1,"msg":"params error","data":null}}

**Comment by kl7sn** [comment]
这个报错原因应该是没有选择数据库。
确认下这个位置是否有对应数据库显示，如果没有可以手动添加下，这里样式逻辑的问题会进行相应的优化。
![WX20220512-150531](https://user-images.githubusercontent.com/2037801/168012024-f3c2aacc-efb2-4b08-b679-86258974acb7.png)

**Comment by ouyangzhongmin** [comment]
感谢！
