### ISSUE TITLE
docker-compose.standalone.yml 启动失败

### ISSUE THREAD

**Issue by xuzhenjun130** [clickvisual/clickvisual#241]
<img width="1231" alt="4a2daea5b94905b136ba6d02430fb18" src="https://user-images.githubusercontent.com/4453516/168052644-589f6ce4-517d-4152-9312-2f6b8dced4a0.png">

**Comment by kl7sn** [comment]
问题已解决，可以参考 https://github.com/clickvisual/clickvisual/issues/232

**Comment by xuzhenjun130** [comment]
@kl7sn 
启动docker正常了
创建数据库失败：

创建实例，填写 dns 参数 tcp://clickhouse:9000?username=root&password=shimo&read_timeout=10&writer_timeout=10&debug=true

弹窗提示异常
```json
{"data":{"code":1,"msg":"DNS configuration exception, database connection failure 01: dial tcp: lookup clickhouse on 127.0.0.11:53: no such host","data":null}}

```

**Comment by kl7sn** [comment]
单机模式下没有启动 clickhouse 服务，可以查看具体的 yml 内容。
体验完整的 Demo 可以使用 docker-compose.yml。
