### ISSUE TITLE
Loading k8s configmap error

### ISSUE THREAD

**Issue by MisachouLu** [clickvisual/clickvisual#245]
添加k8s集群后能获取Configmaps但无法在面板展示内容，点击从k8s同步 error {"data":{"code":1,"msg":"sql: Scan error on column index 12, name \"lock_at\": converting driver.Value type time.Time (\"0001-01-01 00:00:00 +0000 UTC\") to a int64: invalid syntax","data":"sql: Scan error on column index 12, name \"lock_at\": converting driver.Value type time.Time (\"0001-01-01 00:00:00 +0000 UTC\") to a int64: invalid syntax"}}

**Comment by kl7sn** [comment]
本次提交进行了相关修复 https://github.com/clickvisual/clickvisual/pull/249
