### ISSUE TITLE
自建表，时间字段为DateTime64(3)，查询报错

### ISSUE THREAD

**Issue by amuluowin** [clickvisual/clickvisual#246]
错误信息
`{"data":{"code":1,"msg":"query failed: code: 53, message: Type mismatch in IN or VALUES section. Expected: DateTime64(3). Got: UInt64","data":null}}`

**Comment by kl7sn** [comment]
接入已有日志库的场景吗？

**Comment by amuluowin** [comment]
> 

是的

**Comment by kl7sn** [comment]
从报错上看，你已有的日志库字段类型为 UInt64，你选择的字段类型为 DateTime64(3)，二者不匹配。
可以看看已有 table 的 DDL。

**Comment by amuluowin** [comment]
表字段类型确实是DateTime64(3)。
从源码看，在处理查询语句的时候传入的时间为时间戳，`DateTime`和毫秒类型有做处理
`DateTime64(3)`这种类型没有特殊处理，用的整形做条件查询报的错。
应该增加这个类型的判断，然后SQL需要拼接`toDateTime64(param,3)`。
不知道理解得对不对。

**Comment by kl7sn** [comment]
感谢提出问题，相关问题进行了修复。
https://github.com/clickvisual/clickvisual/pull/264

**Comment by amuluowin** [comment]
实测已解决
