### ISSUE TITLE
删除了一个实例以后，同名的数据库无法再创建对应的日志库

### ISSUE THREAD

**Issue by agui2200** [clickvisual/clickvisual#259]
提示：database create failed 03: this table is already exist in clickvisual
就是两个实例，当一个实例已删除，再新建同名同表的日志库就无法创建了

**Comment by kl7sn** [comment]
这个原因应该是在删除过程中对 clickhouse 的操作出现异常，导致删除失败，可以看看数据库里面的目前数据情况。
<img width="867" alt="image" src="https://user-images.githubusercontent.com/2037801/168718255-11076281-af62-4981-b6f9-cb9bdf77b8fe.png">

**Comment by agui2200** [comment]
我刚刚查看了，对应的cv_base_table里面还是存在已删除实例的表

**Comment by kl7sn** [comment]
是的，就是在删除过程中 clickhouse 产生了报错，导致上一个删除流程未完成。

**Comment by agui2200** [comment]
是这样的，我在运行过程中 把clickhouse下线了，下线以后，更换一个新的clickhouse，然后clickvisual的表就遗留，是这个问题？

**Comment by agui2200** [comment]
好的，我是操作过程中将clickhouse下线，然后删除对应clickhouse实例后发生的

**Comment by kl7sn** [comment]
> 好的，我是操作过程中将clickhouse下线，然后删除对应clickhouse实例后发生的

还有其他问题吗？我这边是否可以关闭这个 issues。
