### ISSUE TITLE
【求助】clickhouse数据库中时间是date格式，按时间筛选会报错

### ISSUE THREAD

**Issue by li649779298** [clickvisual/clickvisual#292]
我计划用clickvisual查看clickhouse中的日志信息，但是引入日志表后，按时间筛选会报错。版本是v0.3.0-rc3。
 Code: 386. DB::Exception: There is no supertype for types DateTime64(3), UInt32 because some of them are Date/Date32/DateTime/DateTime64 and some of them are not.
我怀疑是因为clickvisual自动生成的sql语句是将时间换成int类型，但是clickhouse不支持时间格式和int类型的直接比较。

不知道是不是我哪里配置有问题。
![1653562421(1)](https://user-images.githubusercontent.com/106306760/170474249-fd67f3c9-56b9-4f44-a749-696dafe56700.png)
![1653562460(1)](https://user-images.githubusercontent.com/106306760/170474341-1ae11879-8aba-4a03-821a-307441ad2a83.png)

**Comment by kl7sn** [comment]
创建日志库的时候，这个字段类型选的是什么。理论上选择 DateTime 会做一次转换再查询

https://github.com/clickvisual/clickvisual/blob/master/api/internal/service/inquiry/clickhouse.go

看下这个 issues 有没有帮助
https://github.com/ClickHouse/ClickHouse/issues/7306

**Comment by li649779298** [comment]
在我库里是DateTime64(3)，引入日志表的时候选的也是DateTime64(3)，看你贴的代码确实应该是做了转换，但是我这边确实是有这个问题。
![1653565382(1)](https://user-images.githubusercontent.com/106306760/170481416-5246c231-45df-45a4-829f-8b9be877546f.png)

![1653565132(1)](https://user-images.githubusercontent.com/106306760/170481052-d6256cb3-c502-46e4-a3c5-2d0cd9035ba9.png)

在表中看到time_field_type字段是3，改成0之后报错消失，不知道是不是有问题，DateTime64(3)应该是几
![1653566506(1)](https://user-images.githubusercontent.com/106306760/170484086-a07f8ee4-1416-4e8d-a2fd-117cf7e313c4.png)

改成0之后可以查询日志，这里明明查到有3条日志，不知道为什么还会显示”未查到日志“
![1653566632(1)](https://user-images.githubusercontent.com/106306760/170484485-f465f65e-f033-44df-b5bb-0c3a13ea19ee.png)

**Comment by li649779298** [comment]
补充，当表中time_field_type字段是3时，页面上实际的查询log语句是ok的，报错的是后台另一个sql，如下图：
![1653613715(1)](https://user-images.githubusercontent.com/106306760/170608458-f19db31b-2b0a-4161-9485-4c841b07c66b.png)
![image](https://user-images.githubusercontent.com/106306760/170608518-de6fb9d3-7afe-4860-9eb2-5f7136ab6fa1.png)

**Comment by kl7sn** [comment]
time_field_type 字段的含义：
```
const (
	TimeFieldTypeDT   = 0 // DateTime
	TimeFieldTypeDT3  = 3 // DataTime64(3)
)
```

0 对应的查询转换为 toDateTime(1653621362)
3 对应的查询转换为 toDateTime64(xxx, 3)

按照官方文档做 DataTime64类型的数据转换理论上支持精度 https://clickhouse.com/docs/zh/sql-reference/data-types/datetime64/

我推测是否是由于你数据库中该列数据并非全部都是 DataTime64(3) 类型，而 toDateTime 对类型转换比较友好的原因。

**Comment by li649779298** [comment]
**time_field_type为3时查询报错问题**
数据库中的时间格式应该是没有问题，如下图
![1653630484(1)](https://user-images.githubusercontent.com/106306760/170638141-e2efe938-80d3-4ff4-9def-52f85d78f262.png)
从后台查到的sql应该有问题，明明是date64（3）的列，怎么能用1653629229 去比较，不是应该先转成时间格式嘛。
SELECT * FROM `default`.`viem_dlb_ZC_My_syslogs_consumer` WHERE 1='1' AND log_datetime >= 1653629229 AND log_datetime < 1653630129 ORDER BY log_datetime DESC LIMIT 10 OFFSET 0

**数据不一致问题**
我们数据库没有使用集群，是单机部署的。后台查到的sql如下，里面用的是”=“比较，如果我们保存的时间只精确到秒应该是没问题的，因此问题还是上面在type为3的事情。
SELECT * FROM `default`.`viem_dlb_ZC_My_syslogs_consumer` WHERE 1='1' AND (log_datetime = toDateTime(1653621822) or log_datetime = toDateTime(1653621822) or log_datetime = toDateTime(1653621822) or log_datetime = toDateTime(1653621820)) ORDER BY log_datetime DESC LIMIT 10 OFFSET 0

**Comment by li649779298** [comment]
之前定位有些问题，现在的情况是我在clickhouse中执行ok的sql，在页面上执行会报错。。。
查了一下，datetime64（3）是可以和int直接比较的。
SELECT * FROM dlb_ZC_My_syslogs_test WHERE 1='1' AND log_datetime < 1653630129 
![1653644479(1)](https://user-images.githubusercontent.com/106306760/170674602-c01cfda7-a147-4f5a-9369-26540dfb9e86.png)

**Comment by kl7sn** [comment]
`log_datetime >= 1653629229 AND log_datetime < 1653630129`这个查询是 ClickHouse 在底层优化产生的 SQL，代码这边产生的语句是 `%s >= toDateTime64(%s, 3) and %s < toDateTime64(%s, 3)`

查询报错报错的问题可以直接使用下面这个库的 1.5 版本进行本地测试，来比较是否有报错。
https://github.com/ClickHouse/clickhouse-go

**Comment by kl7sn** [comment]
@li649779298 目前情况如何了，我这边可以关闭这个 issues 吗？

**Comment by li649779298** [comment]
问题还没有解决，我最近在忙别的事情，要不你先关了吧。如果大家都没问题，只有我这里出现，应该是哪里没有配对。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "clickvisual/clickvisual"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月6日(星期一) 下午4:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [clickvisual/clickvisual] 【求助】clickhouse数据库中时间是date格式，按时间筛选会报错 (Issue #292)





 
@li649779298 目前情况如何了，我这边可以关闭这个 issues 吗？

**Comment by kl7sn** [comment]
> 问题还没有解决，我最近在忙别的事情，要不你先关了吧。如果大家都没问题，只有我这里出现，应该是哪里没有配对。

那我这边暂时关闭，有问题之后再继续沟通，感谢。
