### ISSUE TITLE
日志内容显示错误：2022-05-27T11:48:04.782+0800: 604360.660: [GC pause (G1 Evacuation Pause)

### ISSUE THREAD

**Issue by wuzhihui1123** [clickvisual/clickvisual#299]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/4246626/170812587-3abb5ce4-f9ec-49d1-b2cb-f3a0e9cc502c.png">
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/4246626/170812603-89b14bfa-7f6e-4c14-b31a-7a49519f605d.png">

所有日志的msg内容页面上都显示为 
`
2022-05-27T11:48:04.782+0800: 604360.660: [GC pause (G1 Evacuation Pause) (young)
Desired survivor size 301989888 bytes, new threshold 1 (max 1)
- age 1: 238254864 bytes, 238254864 total
 604360.660: [G1Ergonomics (CSet Construction) start choosing CSet, _pending_cards: 23914, predicted base time: 13.34 ms, remaining time: 36.66 ms, target pause time: 50.00 ms]
 604360.660: [G1Ergonomics (CSet Construction) add young regions to CSet, eden: 122 regions, survivors: 17 regions, predicted young region time: 37.16 ms]
 604360.660: [G1Ergonomics (CSet Construction) finish choosing CSet, eden: 122 regions, survivors: 17 regions, old: 0 regions, predicted pause time: 50.50 ms, target pause time: 50.00 ms]
, 0.0696159 secs]
 [Parallel Time: 65.1 ms, GC Workers: 16]
 [GC Worker Start (ms): Min: 604360660.1, Avg: 604360660.2, Max: 604360660.2, Diff: 0.2]
 [Ext Root Scanning (ms): Min: 1.6, Avg: 1.8, Max: 2.8, Diff: 1.2, Sum: 28.8]
 [Update RS (ms): Min: 3.6, Avg: 4.2, Max: 5.0, Diff: 1.5, Sum: 67.5]
 [Processed Buffers: Min: 4, Avg: 9.6, Max: 19, Diff: 15, Sum: 154]
 [Scan RS (ms): Min: 0.0, Avg: 0.0, Max: 0.1, Diff: 0.1, Sum: 0.4]
 [Code Root Scanning (ms): Min: 0.0, Avg: 0.0, Max: 0.0, Diff: 0.0, Sum: 0.0]
 [Object Copy (ms): Min: 57.5, Avg: 58.4, Max: 59.0, Diff: 1.5, Sum: 934.8]
 [Termination (ms): Min: 0.0, Avg: 0.4, Max: 0.8, Diff: 0.8, Sum: 5.8]
 [Termination Attempts: Min: 1, Avg: 1.0, Max: 1, Diff: 0, Sum: 16]
 [GC Worker Other (ms): Min: 0.0, Avg: 0.0, Max: 0.1, Diff: 0.1, Sum: 0.6]
 [GC Worker Total (ms): Min: 64.8, Avg: 64.9, Max: 65.0, Diff: 0.2, Sum: 1037.9]
 [GC Worker End (ms): Min: 604360725.0, Avg: 604360725.0, Max: 604360725.1, Diff: 0.1]
 [Code Root Fixup: 0.0 ms]
 [Code Root Purge: 0.0 ms]
 [Clear CT: 0.5 ms]
 [Other: 4.0 ms]
 [Choose CSet: 0.0 ms]
 [Ref Proc: 2.3 ms]
 [Ref Enq: 0.2 ms]
 [Redirty Cards: 0.2 ms]
 [Humongous Regis
`

**Comment by wuzhihui1123** [comment]
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/4246626/170812719-1bb525e4-7c94-42ec-bdf5-af3235058dad.png">

@qianque7

**Comment by kl7sn** [comment]
感谢指出问题，已进行修复 https://github.com/clickvisual/clickvisual/pull/300
