### ISSUE TITLE
【已分配】集成类似 Prom2Click 功能，代理 Prometheus 到 ClickHouse 的读写操作

### ISSUE THREAD

**Issue by kl7sn** [clickvisual/clickvisual#306]

**Comment by auula** [comment]
这个任务怎么做，我不知道怎么使用Prom2Click，还有Prometheus的功能。。。这对应我来说有点困难。

**Comment by askuy** [comment]
> 这个任务怎么做，我不知道怎么使用Prom2Click，还有Prometheus的功能。。。这对应我来说有点困难。

你行的

**Comment by auula** [comment]
> > 这个任务怎么做，我不知道怎么使用Prom2Click，还有Prometheus的功能。。。这对应我来说有点困难。
> 
> 你行的

你给我指导一些，怎么搞，别瞎分配。。。

**Comment by askuy** [comment]
> > > 这个任务怎么做，我不知道怎么使用Prom2Click，还有Prometheus的功能。。。这对应我来说有点困难。
> > 
> > 
> > 你行的
> 
> 你给我指导一些，怎么搞，别瞎分配。。。
好的
