### ISSUE TITLE
【已分配】告警支持其他渠道推送

### ISSUE THREAD

**Issue by kl7sn** [clickvisual/clickvisual#308]
参考开发文档 https://clickvisual.gocn.vip/clickvisual/06join/alert-push-channel.html

**Comment by ArthurQiuys** [comment]
# 预计增加推送渠道
1. 飞书
2. Slack
3. telegram
4. pluspush
5. server酱

**Comment by kl7sn** [comment]
目前告警产生的内容`var buffer bytes.Buffer`这个部分是在下面这个文件中构建的，你开发的过程可以考虑告警内容做成通用函数，然后做参数传到各个渠道。这是个优化点。

https://github.com/clickvisual/clickvisual/blob/master/api/pkg/push/dingding.go

**Comment by auula** [comment]
这个有人做吗？
