### ISSUE TITLE
关于clickvisual的一些问题

### ISSUE THREAD

**Issue by ktpktr0** [clickvisual/clickvisual#350]
1、clickvisual性能测试报告？特别是与ELK在同等规模下的对比测试。
2、哪些组件是必需？
3、组件是否可以使用已有的，而不是新建。
4、目前只能测试使用？上生产环境没有集群版？
5、目前哪些企业已使用该日志平台？

**Comment by kl7sn** [comment]
@ktpktr0 刚刚在QA文档对以上问题进行了回答。

[https://clickvisual.gocn.vip/clickvisual/01quickstart/qa.html](https://clickvisual.gocn.vip/clickvisual/01quickstart/qa.html)

**Comment by ktpktr0** [comment]
感谢，关于问题4，似乎没有提供集群版部署的方案，只有单组件的版本。

**Comment by kl7sn** [comment]
在编辑 ClickHouse 数据源的时候进行选择就可以了

![image](https://user-images.githubusercontent.com/2037801/173274089-b48686b7-d7b2-471a-8e2a-42cda11d977e.png)

**Comment by ktpktr0** [comment]
那其它组件不需要集群？

**Comment by kl7sn** [comment]
> 那其它组件不需要集群？

其他组件指的是？
