### ISSUE TITLE
【可认领】文档翻译代码仓库为 clickvisual/clickvisual-doc

### ISSUE THREAD

**Issue by kl7sn** [clickvisual/clickvisual#360]

**Comment by kl7sn** [comment]
@changpingdengdeng

**Comment by rotk2022** [comment]
具体怎么操作？

**Comment by kl7sn** [comment]
<img width="276" alt="image" src="https://user-images.githubusercontent.com/2037801/173310916-347ee91b-f0e3-421a-b0ce-c846cd941ddb.png">

/en/ 目录下的文本内容翻译为英文就好了，中文如果觉得描述不通畅也可以调整。
