### ISSUE TITLE
通过已有数据表接入的能管理分析字段吗？

### ISSUE THREAD

**Issue by liu-yfeng** [clickvisual/clickvisual#436]
这些字段能自己删除，添加吗
![image](https://user-images.githubusercontent.com/8706840/175457967-fb0af81c-4a88-48f9-a576-92d8fbbbe341.png)

**Comment by kl7sn** [comment]
接入已有表是直接使用了目标表的字段。
设计原则上对已有表的操作是只读，所以不支持修改，避免破话原表。
