### ISSUE TITLE
请问权限管理怎么配置

### ISSUE THREAD

**Issue by duyingsoft** [clickvisual/clickvisual#457]
“系统管理” -> "权限管理"，只有创建角色，然后角色怎么分配给用户，好像没有地方没有配置？

**Comment by kl7sn** [comment]
在实例管理的部分，可以管理对 clickhouse 的操作权限。
![image](https://user-images.githubusercontent.com/2037801/176580153-54bdcd53-5bf2-4ea3-bbba-f8dc91049833.png)

**Comment by hasylu** [comment]
新建用户只能通过gitlab或者github吗

**Comment by hasylu** [comment]
> 也可以使用代理方式登录 https://clickvisual.gocn.vip/clickvisual/04appauth/auth-proxy.html

我已经通过一个骚操作解决了，直接去mysql对应的表里面创建多一条记录，给个默认密码
