### ISSUE TITLE
日志显示问题

### ISSUE THREAD

**Issue by liu-yfeng** [clickvisual/clickvisual#474]
原始日志里面这里是没有空格的，这里显示多了一个空格
![image](https://user-images.githubusercontent.com/8706840/176877338-5810770d-b6c9-43c9-ad95-6f5e7ac8a16f.png)
![image](https://user-images.githubusercontent.com/8706840/176877470-0fd9f787-b382-4435-80aa-7dc16543517e.png)

**Comment by kl7sn** [comment]
@m1666 看下是否是数据内容解析的时候产生的问题

**Comment by m1666** [comment]
方便提供下原始日志嘛？我尝试过一些办法去复现定位，可是都没有成功。

![image](https://user-images.githubusercontent.com/39024186/177067978-ceaca30a-12bd-457e-8bb5-612034c634e6.png)

**Comment by liu-yfeng** [comment]
![image](https://user-images.githubusercontent.com/8706840/177302893-b872b441-7967-46cc-83ee-28571f44dc11.png)

**Comment by m1666** [comment]
`{
      level: "INFO",
      project: "xxxxxx",
      raw_log:
        '2022-07-04 16:54:31.8009||INFO||xxxxx,结束时间小于当前结束时间=12/31/2022 00:00:00,{\n "version": "v2.5",\n "key": "xxxxxx",\n "timestamp": "2022070416543333",\n "data": "{"version":"V1.8","key":"xxxxxx","carNo":"豫EXN772","beginTime":"2020-09-29","endTime":"2022-06-30","chargeTime":"2022-07-04 16:54:30","chargeMoney":"0.00","operatorName":"888888-管理员","carType":"3654"}",\n "sign": "4F073C3897C7B49CC654C93C9A4E959C"\\n} \n\r\n',
      source: "e",
      time_nanosecond: "2022-07-04T16:54:31.800900096+08:00",
      time_second: "2022-07-04T16:54:31+08:00",
    }`
    
  我尝试使用上面的 JSON，在 0.3.1-rc3 上进行复现，没有复现成功。
![image](https://user-images.githubusercontent.com/39024186/177314644-7d3e1f8d-3b78-4d6b-9f19-92102ed37e11.png)
方便把接口里面的 data 发出来吗？或者远程看看可以吗？
![image](https://user-images.githubusercontent.com/39024186/177315274-a9390d61-4db2-4b19-83c4-1d4931b5d00e.png)

**Comment by m1666** [comment]
麻烦提供整个 logs 接口返回的参数吗？

![image](https://user-images.githubusercontent.com/39024186/177456040-cb95ec85-6746-466a-bbfe-646d2e0e3f95.png)

**Comment by liu-yfeng** [comment]
返回的格式是对的
![image](https://user-images.githubusercontent.com/8706840/177500009-9442c272-f62b-4828-ac49-b74fbd156ca8.png)

**Comment by m1666** [comment]
`{
    "level": "INFO",
    "project": "xxxxxx",
    "raw_log": "2022-07-04 16:54:31.8009||INFO||xxxxx,结束时间小于当前结束时间=12/31/2022 00:00:00,{\n \"version\": \"v2.5\",\n \"key\": \"xxxxxx\",\n \"timestamp\": \"2022070416543333\",\n \"data\": \"{\\\"carNo\\\":\\\"豫EXN772\\\"}\",\n \"sign\": \"4F073C3897C7B49CC654C93C9A4E959C\"\\n} \n\r\n",
    "source": "e",
    "time_nanosecond": "2022-07-04T16:54:31.800900096+08:00",
    "time_second": "2022-07-04T16:54:31+08:00"
  }`
![image](https://user-images.githubusercontent.com/39024186/177531862-c91f3e64-a97e-4950-9cbc-1baaed1561f6.png)
上面是我参考上面截图 mock 的数据和使用该数据测试的结果，如果进一步排查的话，还是需要把接口返回的数据，敏感数据麻烦你手动过滤一下，发给我们一下。

**Comment by liu-yfeng** [comment]
换了一个浏览器显示就没问题了，谢谢！

**Comment by kl7sn** [comment]
没问题就行，那我们这边关闭 issues 了，感谢反馈问题，如果方便，可以帮忙简要登记下你们的使用信息，后期这边做宣传使用。  

相关issues：https://github.com/clickvisual/clickvisual/issues/154
