### ISSUE TITLE
ClickVisual 支持 "展示上下文" 功能吗

### ISSUE THREAD

**Issue by wangchaoforever** [clickvisual/clickvisual#506]
根据条件搜索出日志结构后，需要查看某条日志的上下文，请问 ClickVisual 有 "展示上下文" 功能吗？

**Comment by kl7sn** [comment]
暂时不支持这个功能，看是否可以用链路id或者文件关键字手动过滤下。

**Comment by wangchaoforever** [comment]
请问有这个计划加上这个功能吗？这个功能比较快捷

**Comment by kl7sn** [comment]
暂时没有这个开发计划。这边还是建议使用规范性的关键字方式进行日志查询。日志上下文在量级大的情况下，可能效率不高。
