### ISSUE TITLE
增加数据按照列下载功能

### ISSUE THREAD

**Issue by xg0719** [clickvisual/clickvisual#520]
用户查到数据后，很多时候需要按需将指定特征的数据导出，方便进一步处理或者给相关人员查看，因此建议增加数据按照列下载功能
1. 用户先按需过滤数据
2. 用户可以选择指定的列，并导出为 csv 或 excel

**Comment by kl7sn** [comment]
目前可以在这个页面，手动调整 select 的内容，然后再导出，你看下是否可以满足需求。

![image](https://user-images.githubusercontent.com/2037801/179657703-15bb46a8-c11a-40cc-943a-8dd1879ddfcd.png)

**Comment by xg0719** [comment]
好的，感谢，通过 select 来选择列也可以;
另外，我用 https://clickhouse.com/docs/zh/getting-started/example-datasets/uk-price-paid/ 数据源测试，导出的时候发现 limit 不论设置100还是1000 都只返回19条数据，实际上查询最近2年有170多万条数据，麻烦有空的话帮忙确认下这个功能是否有待完善
![image](https://user-images.githubusercontent.com/23369777/179714872-214e6adb-e917-45c9-ab03-7761e915a42a.png)

**Comment by kl7sn** [comment]
可以确认下你的筛选条件是否只有19条数据。我这边测试100条数据导出，确实是100条。

![image](https://user-images.githubusercontent.com/2037801/179718326-ad6053df-ed0f-4cca-aea4-0cbcdae0f665.png)
<img width="752" alt="image" src="https://user-images.githubusercontent.com/2037801/179718431-cda3277c-2e28-4bf9-b3bc-0f003f5755c4.png">

**Comment by xg0719** [comment]
有2个问题，如果能优化下就好了：
问题1：
默认前端点击查询，时间为最近2年，切换到导出数据时候它默认的sql语句是多个 date = toDateTime(1653494400) 类似的条件检索，而不是 date >= toDateTime(1595379780) and date < toDateTime(1658451780) 的区间检索
![image](https://user-images.githubusercontent.com/23369777/180341414-e121500d-54d2-4d74-8a61-9b1ece0604a2.png)

问题2：
这个语句limit大于100的时候只能输出100条，但是实际上把这个语句放在 clickhouse-client 中查询是101条
SELECT * FROM `default`.`uk_price_paid2` WHERE 1='1' AND date >= toDateTime(1595379780) and date < toDateTime(1658451780) ORDER BY date DESC LIMIT 101 OFFSET 0

查询最近2年数据，LIMIT 101 OFFSET 0 时候只能输出100条
![image](https://user-images.githubusercontent.com/23369777/180341548-71e96221-7fed-4a9a-84a4-1be2af2ababf.png)
实际在clickhouse-client 中查询是101条
![image](https://user-images.githubusercontent.com/23369777/180341665-a2693e01-1c5f-4cbb-ad35-fbefda49706b.png)

**Comment by kl7sn** [comment]
在 https://github.com/clickvisual/clickvisual/releases/tag/v0.3.2-rc4 进行了相关修复优化，可以更新版本体验下。

**Comment by xg0719** [comment]
[v0.3.2-rc4](https://github.com/clickvisual/clickvisual/releases/tag/v0.3.2-rc4) 看上去是ok的，辛苦大佬了

**Comment by kl7sn** [comment]
> [v0.3.2-rc4](https://github.com/clickvisual/clickvisual/releases/tag/v0.3.2-rc4) 看上去是ok的，辛苦大佬了

ok~ 那我关闭这个 issues 了
