### ISSUE TITLE
[Feature Request] rootURL support for multiple domains

### ISSUE THREAD

**Issue by laojianzi** [clickvisual/clickvisual#530]
https://github.com/clickvisual/clickvisual/blob/7b04f76a5ce5f4c42c820fbac21a6f3a87c5dbbd/config/default.toml#L4

**Comment by kl7sn** [comment]
如果配置多域名支持，在完成登录的时候跳转到哪个地址？

**Comment by laojianzi** [comment]
> 如果配置多域名支持，在完成登录的时候跳转到哪个地址？

---
以下一个未经过测试的想法 ...

https://github.com/clickvisual/clickvisual/blob/1fe180de3b768f0eba8f1f5f54e9d902b51c18a8/api/internal/apiv1/user/oauth.go#L69-L76
- 这里的 `AuthCodeURL` 可以传入一个自定义的 `oauth2.SetAuthURLParam("redirect_uri", c.Request.Host + url prefix + baseURL)`
- 添加一个 url prefix 配置来支持 `https://domain/clickvisual` 而不限制域名，使用 `request domain + url prefix` 来替代 `rootURL` 

@kl7sn 不知道这样是否能够覆盖到 `rootURL` 的使用场景

**Comment by kl7sn** [comment]
你的需求是？不同的登录方式回调到不通的登录地址？
github -> 域名A
gitlab -> 域名B

目前从代码上看，这部分的鉴权跳转地址和 rootURL 没关联， rootURL 的作用范围：
- 鉴权失败后的回调地址
- 告警推送三方后的跳转地址
- 子路径模式下提供子路径解析

**Comment by laojianzi** [comment]
> 你的需求是？不同的登录方式回调到不同的登录地址？ github -> 域名A gitlab -> 域名B
> 
> 目前从代码上看，这部分的鉴权跳转地址和 rootURL 没关联， rootURL 的作用范围：
> 
> * 鉴权失败后的回调地址
> * 告警推送三方后的跳转地址
> * 子路径模式下提供子路径解析

- 多网关
  - 外部网关
  - 内部网关

- 一个域名代表一种权限
  - 只读
  - root
  - 限定部分编辑

**Comment by kl7sn** [comment]
你看下这种方式登录是否可以 https://clickvisual.gocn.vip/clickvisual/04appauth/auth-proxy.html

可以满足两种权限
1. root
2. 普通用户

**Comment by laojianzi** [comment]
> 你看下这种方式登录是否可以 https://clickvisual.gocn.vip/clickvisual/04appauth/auth-proxy.html
> 
> 可以满足两种权限
> 
> 1. root
> 2. 普通用户

一般都是通过网关的反向代理来控制 proxy header，所以这里是不是仍然需要两个域名？
或者说有其他方式可以注入这个 header 避免多域名吗？

**Comment by kl7sn** [comment]
我们这边的使用方式是一个域名，然后根据不同的用户写入不同的 header。

**Comment by laojianzi** [comment]
> 我们这边的使用方式是一个域名，然后根据不同的用户写入不同的 header。

@kl7sn 请教一下，如何使用 iframe 的时候写 header，如果跨域也可以满足吗？

**Comment by kl7sn** [comment]
这个鉴权方式，最合适的使用方式是子路径模式 https://clickvisual.gocn.vip/clickvisual/03funcintro/subpath-configuration.html 这个参考 Grafana 的使用。

**Comment by laojianzi** [comment]
我理解 Grafana 的 iframe 使用方式也是只能指定一个 header 的，例如: https://clickvisual.gocn.vip/grafana 设置的 /grafana 反响代理自动添加 header xxx

所以，我现在的想法一直是
> 当我们指定了 rootURL 是一个固定地址时，没办法判断使用不同的 header token

**Comment by kl7sn** [comment]
子路径模式下整个鉴权流程是在 clickvisual.gocn.vip 中完成

<img width="906" alt="image" src="https://user-images.githubusercontent.com/2037801/181408585-7f091dc8-c0ac-4d6a-8bf4-0cd8666ef5f9.png">

**Comment by laojianzi** [comment]
明白，所以 clickvisual 只是把判断标识自己自定义了，如果只是引入网关而不自定义应该只能通过不同的域名来达到判断的条件吧？

**Comment by kl7sn** [comment]
可以这样试试，理论上可行。

**Comment by laojianzi** [comment]
> 可以这样试试，理论上可行。

这就回到了原来的问题，clickvisual 不支持多域名 :(

**Comment by kl7sn** [comment]
那你们怎么部署 Grafana 的？可以考虑再加一层网关解决

**Comment by laojianzi** [comment]
> 那你们怎么部署 Grafana 的？可以考虑再加一层网关解决

你是对的，我过于执着应用能力了 ...
thx

**Comment by kl7sn** [comment]
嗯，解决了就好，那我关闭这个 issues 了。
