### ISSUE TITLE
表包含map类型时会报错

### ISSUE THREAD

**Issue by xg0719** [clickvisual/clickvisual#536]
日志业务中会将未知的字段统一放在map中，当前表有map字段的时候会报错，能否优化或者给出相应方案
![image](https://user-images.githubusercontent.com/23369777/181145584-1c776a38-6a87-4635-9c3d-0ff266275f76.png)

**Comment by kl7sn** [comment]
相关 issues https://github.com/clickvisual/clickvisual/issues/434

**Comment by xg0719** [comment]
> 

测试环境：
clickhouse : 22.2.2.1
clickvisual :  clickvisual-v0.3.2-rc4

**Comment by kl7sn** [comment]
https://github.com/clickvisual/clickvisual/commit/22363ba516a1d014b55e059a1e56f94f2424ca97

本次提交将 clickhouse-go 从 v1.5.4 升级到了 v2.2.0，本地测试可以正常支持 Map 了
你可以尝试使用最新代码，或等本周五 ClickVisual 的版本发布

**Comment by xg0719** [comment]
> 

已经测试，可以正常看map类型的数据，辛苦大佬了
