### ISSUE TITLE
[Feature Request] 搜索内容没有形成 SQL 语法时默认 _raw_log_ LIKE 提交

### ISSUE THREAD

**Issue by laojianzi** [clickvisual/clickvisual#551]
例如: search `foo bar` 等同于 `'foo bar'` 等同于 `"foo bar"`
查询: `_raw_log_ LIKE '%foo bar%'`

**Comment by kl7sn** [comment]
这个可以考虑，之前没进行开发主要原因是不建议使用 like 查询，所以没有针对性优化这个部分的性能。

**Comment by kl7sn** [comment]
感谢反馈，已完成相关优化：https://github.com/clickvisual/clickvisual/commit/60ff363b4374eab2ba7830d8efbef82da783f69c
