### ISSUE TITLE
功能优化建议：搜索框使用or导致分区失败的优化

### ISSUE THREAD

**Issue by hasylu** [clickvisual/clickvisual#557]
![1660026767557](https://user-images.githubusercontent.com/3271307/183580703-c1dafa14-a053-4652-9e99-70eec391ae2d.jpg)

如截图所示，使用前面message like 的时候，可以按时间分区走，但加上or之后，组装成的SQL就会导致分区失败，直接全表扫描了，实际上用户想要的应该还是在分区时间内的OR条件，建议拼接SQL的时候，使用括号将搜索框架里面的包含起来，这样无论如何，都可以按时间分区

**Comment by kl7sn** [comment]
感谢反馈，已修复相关问题：https://github.com/clickvisual/clickvisual/pull/559

**Comment by hasylu** [comment]
修复速度也太快了吧

**Comment by kl7sn** [comment]
优先解决 BUG
