### ISSUE TITLE
分析字段带有_host,开启hash 的时候, 用字段查询报错,查询语句生成的字段名称错误

### ISSUE THREAD

**Issue by axingblog** [clickvisual/clickvisual#558]
版本:0.4.0-rc1
clickhouse: 21.8.4.51
查询条件: upstream_proxy_host='fabio-crm-api'
实际查询为:upstream_proxy__inner_siphash_host_ = sipHash64('fabio-crm-api')
clickhouse 实际字段为:  `_inner_siphash_upstream_proxy_host_`
 
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/5227772/183584202-66a401b4-482f-4993-b681-9b4be4d5b8ef.png">
<img width="1597" alt="image" src="https://user-images.githubusercontent.com/5227772/183584319-f8df15e1-4faa-4332-98c5-fe9f58f0cf21.png">
<img width="565" alt="image" src="https://user-images.githubusercontent.com/5227772/183584735-76f84221-6c4b-4eb4-8930-b7b385115b6d.png">

**Comment by kl7sn** [comment]
感谢反馈，已完成相关修复：https://github.com/clickvisual/clickvisual/pull/560

**Comment by axingblog** [comment]
@kl7sn  使用2022-08-10T10:22:16.202964769Z 构建的clickvisual/clickvisual:master 镜像 还是报错

**Comment by kl7sn** [comment]
我这边自测是在以下模式d的时候会出现这个报错。
<img width="869" alt="image" src="https://user-images.githubusercontent.com/2037801/184090568-378d4832-bb1a-4153-8925-de4c5ec6d8cf.png">

构建完成是否为重新配置分析字段的操作。如果是重新配置的。

**Comment by kl7sn** [comment]
可核对下数据表 cv_base_index 里面的字段是否和这个单测的字段吻合。

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/2037801/184092027-36f54eae-3acd-4c44-927d-6868aeec9690.png">

**Comment by axingblog** [comment]
cv_base_index  中的配置是
<img width="625" alt="image" src="https://user-images.githubusercontent.com/5227772/184093349-527b9d20-040e-44e6-87a2-e5716f969ef8.png">

**Comment by kl7sn** [comment]
再次测试无法复现你的情况。

![image](https://user-images.githubusercontent.com/2037801/184273811-ef74a689-1965-440f-b1ac-f42dfefe8ec8.png)

![image](https://user-images.githubusercontent.com/2037801/184273893-93940000-5d14-45a3-866f-7a6019f92b2e.png)

<img width="362" alt="image" src="https://user-images.githubusercontent.com/2037801/184273960-4b86beee-abe1-4aa7-b48d-4266f3878208.png">

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/2037801/184274034-fd1226e2-c95c-4094-aa7b-cdb4e5157e2b.png">

**Comment by kl7sn** [comment]
![image](https://user-images.githubusercontent.com/2037801/186343955-3f1db1a1-7d5d-4079-b891-ae67ce95f85f.png)

这个原因应该是 proxy_name 和 upstream_proxy_name 进行 key 替换的时候出现了歧义。
你先至开启 upstream_proxy_name 的配置，关闭其他的字段 hash，我这边立刻进行修复。
