### ISSUE TITLE
客户端埋点日志是否适用？

### ISSUE THREAD

**Issue by shushenghong** [clickvisual/clickvisual#562]
麻烦问下clickvisual除了后端的日志收集，是否适用客户端埋点日志收集？

**Comment by askuy** [comment]
可以使用的，我们现在用的就是otel，采集前后端的性能日志。

**Comment by askuy** [comment]
> 麻烦问下clickvisual除了后端的日志收集，是否适用客户端埋点日志收集？

可以使用的，我们现在用的就是otel，采集前后端的性能日志。

**Comment by hanwenbo** [comment]
@askuy 假如我有个app  app请求我的服务器  我的服务器再请求clickvisual服务  需要怎么做 我看文档里的api里没有通过接口传日志的
