### ISSUE TITLE
新增日志库后希望可以增加修改的功能

### ISSUE THREAD

**Issue by bruse-peng** [clickvisual/clickvisual#563]
新增日志库后希望可以增加修改的功能，比如我增加了日志库，设置的日志保留时间是3天，但是有一天我想改为7天，目前是不支持修改的，希望增加修改的功能。

**Comment by kl7sn** [comment]
可以的，目前列入开发计划中。

**Comment by hasylu** [comment]
赞同，不过每次加个表都要全部再点一次

**Comment by kl7sn** [comment]
master 分支已支持修改，8.26 会推出稳定版本
![image](https://user-images.githubusercontent.com/2037801/186559751-89a630e0-66f7-4c30-a6b8-5d042c8fb4f5.png)
