### ISSUE TITLE
新增clickhouse集群失败

### ISSUE THREAD

**Issue by ywzrb** [clickvisual/clickvisual#576]
![企业微信截图_613ba081-4198-4688-8de8-b2dcc1feed13](https://user-images.githubusercontent.com/51774120/184833266-962b7e4d-8888-4e5b-bb2e-5ab174a11473.png)
![企业微信截图_306176c0-1b21-4259-87d9-0a3f7ec8db66](https://user-images.githubusercontent.com/51774120/184833295-1dd41798-b684-46b2-a0f4-897c9bba6935.png)

clickvisual用helm部署，clickhouse集群也是helm部署（3分片2副本）

**Comment by kl7sn** [comment]
![image](https://user-images.githubusercontent.com/2037801/184861968-2332e867-833a-447a-bd1c-d75c56c4295c.png)
这里要填写 cluster 名称

**Comment by ywzrb** [comment]
解决了
