### ISSUE TITLE
新增clickhouse实例失败，报需要root超级管理员权限

### ISSUE THREAD

**Issue by 15827493947** [clickvisual/clickvisual#579]
![image](https://user-images.githubusercontent.com/29707738/185022977-c7821f64-56a8-45d5-a2b5-343d7404d063.png)

**Comment by kl7sn** [comment]
初始化的时候权限载入失败导致的，具体原因是升级了 Casbin 的版本后没有覆盖这个部分的测试，相关修复已提交 https://github.com/clickvisual/clickvisual/commit/760cdcb06c699d8e15e8f9f2600f1e81a80a5776

**Comment by 15827493947** [comment]
> 初始化的时候权限载入失败导致的，具体原因是升级了 Casbin 的版本后没有覆盖这个部分的测试，相关修复已提交 [760cdcb](https://github.com/clickvisual/clickvisual/commit/760cdcb06c699d8e15e8f9f2600f1e81a80a5776)

我点击数据库结构升级后问题已解决，这个是必须要点数据库升级嘛？

**Comment by kl7sn** [comment]
不是必须的，是权限模块升级后产生的问题。

**Comment by 15827493947** [comment]
了解
