### ISSUE TITLE
接入已有数据库，kafka引擎表无法导入

### ISSUE THREAD

**Issue by ywzrb** [clickvisual/clickvisual#580]
![image](https://user-images.githubusercontent.com/51774120/185078669-288f64af-7504-4508-9ad7-cca3664ffc6d.png)
![image](https://user-images.githubusercontent.com/51774120/185080124-cd4d2f9b-2b79-46ef-a08f-24a6aaa6050b.png)

接入数据的时候只要选择本地表k8s_log_local就行吗

**Comment by kl7sn** [comment]
你这个情况，应该直接入 distribute 表就可以了。

**Comment by ywzrb** [comment]
好的
