### ISSUE TITLE
Mogo文档-石墨文档日志架构一文中有两处排版问题

### ISSUE THREAD

**Issue by 15827493947** [clickvisual/clickvisual#585]
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/29707738/185350997-6e5a3c58-4d52-4ac3-ab0f-cb9e602ca6d8.png">

**Comment by kl7sn** [comment]
新版本的文档地址

https://clickvisual.gocn.vip/

**Comment by 15827493947** [comment]
👌🏻
