### ISSUE TITLE
clickvisual日志时间不准确可以修改吗

### ISSUE THREAD

**Issue by SHPyel** [clickvisual/clickvisual#603]
![image](https://user-images.githubusercontent.com/17775511/186562486-71c6cff8-ac2a-4320-aab2-b12698edb261.png)

**Comment by kl7sn** [comment]
clickvisual 版本是多少？

 `_time_nanosecond_ `字段值是多少？

是否配置过这个功能？
<img width="301" alt="image" src="https://user-images.githubusercontent.com/2037801/186573332-74a5dd7f-a97a-4429-8fd7-e8b9e89351a9.png">

**Comment by SHPyel** [comment]
![image](https://user-images.githubusercontent.com/17775511/186583588-19db2f8a-4a15-4b6a-ae8c-3a1fc8431dfc.png)
版本是这个镜像：sevennt/mogo:master ，然后下载二进制clickvisual-v0.4.0-rc3-linux-amd64.tar.gz 这个也试过。
表是创建好直接使用的，没有配置采集规则。
_time_nanosecond_ :1661405758 看了这个字段值不对，取的是秒，不是微秒

**Comment by kl7sn** [comment]
<img width="737" alt="image" src="https://user-images.githubusercontent.com/2037801/186850368-057abc8d-2840-45c6-994f-81facebf74a8.png">
可以看下物化试图里面对该字段的转换语句

**Comment by kl7sn** [comment]
这个转换是读取原始日志的时间字段进行的，上面的问题应该是这个转换没有达到符合的精度。

**Comment by SHPyel** [comment]
可以了 多谢哈
![image](https://user-images.githubusercontent.com/17775511/187117560-eeddd1b5-43aa-4331-ae39-9eabee0040a5.png)
