### ISSUE TITLE
权限管理模块，自定义角色控制资源显示失效

### ISSUE THREAD

**Issue by imgolye** [clickvisual/clickvisual#606]
角色配置指定的资源权限，其他资源不应该展示，如只配置了日志，报警、分析这两个模块菜单不应该显示。

**Comment by imgolye** [comment]
角色配置指定的资源权限，其他资源不应该展示，如只配置了日志，报警、分析这两个模块菜单不应该显示。

**Comment by kl7sn** [comment]
@imgolye https://github.com/clickvisual/clickvisual/commit/455bcb451822c2786db89997eecd7b69a65288d4
