### ISSUE TITLE
日志折叠状态下，添加查询条件的时候会多双引号

### ISSUE THREAD

**Issue by wuzhihui1123** [clickvisual/clickvisual#618]
<img width="983" alt="image" src="https://user-images.githubusercontent.com/4246626/189260784-bd772bf6-0245-4488-b39a-dd075e404bfb.png">
<img width="984" alt="image" src="https://user-images.githubusercontent.com/4246626/189260893-bb5ed22c-1997-4a10-9480-d40abd494128.png">

**Comment by qianque7** [comment]
多谢反馈，该问题已在master分支修复

**Comment by qianque7** [comment]
https://github.com/clickvisual/clickvisual/commit/35f38c50c0d7af57d74a0ea67a0533990f39a981
