### ISSUE TITLE
创建告警时，提示MergeTree engine is deprecated

### ISSUE THREAD

**Issue by dengpei89** [clickvisual/clickvisual#620]
数据源是clickhouse

表结构
CREATE TABLE student_mt(
	id Int,
	sno String,
	name String,
	cno String,
	create_time DateTime
)
ENGINE = MergeTree
PARTITION BY create_time
ORDER BY create_time;

在检查统计中的查询框中输入了name = 'alex'，预览中能看到数据，但一直报错，错误如下：
请求失败
错误：alarm create failed 02: code: 36, message: This syntax for *MergeTree engine is deprecated. Use extended storage definition syntax with ORDER BY/PRIMARY KEY clause.See also allow_deprecated_syntax_for_merge_tree setting.

clickvisual版本是v0.4.0
clickhouse版本是：

ClickHouse client version 22.8.2.11 (official build).
ClickHouse server version 22.8.2.11 (official build).

**Comment by kl7sn** [comment]
直接用命令行连接 ClickHouse 可以正常查询吗？

**Comment by dengpei89** [comment]
> 直接用命令行连接 ClickHouse 可以正常查询吗？
可以的，没什么问题，不知道是不是clickhouse版本兼容问题？

**Comment by kl7sn** [comment]
情况是，预览成功，点击告警保存后报错，对吧。

报错原因应该是物化试图创建失败。
你可以过滤下日志，clickvisual.log 中，关键字为 alarm 和 error，可以看到 viewSQL 字段，这个字段为物化视图 SQL。

**Comment by dengpei89** [comment]
好的， 我试试，谢谢

**Comment by dengpei89** [comment]
降低clickhouse版本后，问题解决。
目前的版本是V21.12.3.32
