### ISSUE TITLE
关于_time_和_log_这两个字段是否可以采用默认值

### ISSUE THREAD

**Issue by learning-go123** [clickvisual/clickvisual#621]
例如：
`_time_`的默认值Timestamp，`_log_` 默认值就是Value

<img width="957" alt="image" src="https://user-images.githubusercontent.com/88469563/189305990-8860b270-f1fe-47d6-8f8c-bf3bef694e9c.png">

这么做的好处是采集端无需在打包一次json, 减轻了采集端的一些压力
多余的字段可以放在Headers里

**Comment by kl7sn** [comment]
目前最新版本支持这个功能
<img width="895" alt="image" src="https://user-images.githubusercontent.com/2037801/189334404-bc1f9db4-cd57-419b-80b0-9798aaeaa123.png">

**Comment by kl7sn** [comment]
可以使用 https://github.com/clickvisual/clickvisual/releases/tag/v0.4.1 体验下。

**Comment by learning-go123** [comment]
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/88469563/189796882-e28c69cf-bf38-44fb-aaae-ebcaf078a410.png">
试了下没有，是我使用的问题吗？

**Comment by kl7sn** [comment]
前端缓存？

**Comment by learning-go123** [comment]
是缓存
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/88469563/189812037-d3e22026-02f0-49ed-b540-68c5544bc796.png">
测试了好几次，我给字段加上索引。后面的数据就不显示了 kafka里面有数据

支持给kafka的中的Headers加索引吗？

**Comment by kl7sn** [comment]
这个目前还不支持，可以列入开发计划，尽量本周完成支持。

**Comment by kl7sn** [comment]
https://github.com/clickvisual/clickvisual/releases/tag/v0.4.2-rc3 使用 JSONAsString 方式创建日志库，支持了 headers 显示。
<img width="344" alt="image" src="https://user-images.githubusercontent.com/2037801/192187607-4e443849-5caa-4c65-a7cb-1bf1457256f1.png">

**Comment by learning-go123** [comment]
@kl7sn 看到了，但是索引还没支持是吗？

**Comment by kl7sn** [comment]
你这里说的索引值的是分析对于类型的百分比吗？

**Comment by learning-go123** [comment]
这边我加了分析key1字段，后面的数据就看不到了
删掉这个key1分析字段也不行

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/88469563/192423655-b8457582-0c64-40ce-8451-dcb888263585.png">

**Comment by kl7sn** [comment]
相关修复：https://github.com/clickvisual/clickvisual/commit/c344cb8becae40cdb14e1653075988ebd9ea8a98
关联版本：https://github.com/clickvisual/clickvisual/releases/latest

更新代码，再次删除或新增分析字段后可恢复。

**Comment by learning-go123** [comment]
感谢大佬，没什么问题了. 目前已经满足我的需求了
后面等大佬有时间再优化
