### ISSUE TITLE
配置告警时，提示prometheus的rules路径不存在，无法创建rule

### ISSUE THREAD

**Issue by dengpei89** [clickvisual/clickvisual#622]
clickvisual后台日志：
{"lv":"error","ts":1663053027,"msg":"alarm","step":"alarm create failed 09","err":"open /opt/bitnami/rules/cv-3da6cb78-11ff-4378-b23c-19f5d29b085d.yaml: no such file or directory"}
{"lv":"warn","ts":1663053027,"msg":"biz warning","value":"alarm create failed 02: open /opt/bitnami/rules/cv-3da6cb78-11ff-4378-b23c-19f5d29b085d.yaml: no such file or directory","value":null,"tid":"77939ae5d8288a9dffea138874977ee

cat prometheus.yaml 
alerting:
  alertmanagers:
  - static_configs:
    - targets: ["172.17.0.1:9093"]
rule_files:
  - /opt/bitnami/rules/*.yaml
remote_read:
  - url: "http://172.17.0.1:9201/read"
    read_recent: true
remote_write:
  - url: "http://172.17.0.1:9201/write"
    queue_config:
      capacity: 10000
      max_shards: 1
      max_samples_per_send: 500

手动在 /opt/bitnami/rules/目录下创建rule，没有问题，prometheus的页面可以识别到。

**Comment by kl7sn** [comment]
看下是不是没有写权限

**Comment by dengpei89** [comment]
777吗， 因为prometheus用的是bitnami的镜像。
/opt/bitnami/rules 目录挂载到宿主机的/data/rules，按bitnami的要求，将id为1001设置为/data/rules目录的owner

**Comment by kl7sn** [comment]
这部分的逻辑是写文件，写入失败大概率是没权限。

**Comment by dengpei89** [comment]
找到原因了，之前以为这个rule会写到prometheus里的/opt/bitnami/rules目录。
最后测试了下，发现是写入到clickvisual这台机器，而clickvisual这台机器是没有/opt/bitnami/rules目录，只有/data/rules目录（实际是mount到prometheus容器里的/opt/bitnami/rules），所以文件路径直接更改为/data/rules即可创建成功。
另外建议，尽量以案例的形式完善文档，如果对prometheus和clickhouse不熟悉的人，很难部署成功。

**Comment by kl7sn** [comment]
会尽快更新文档，十分感谢。
