### ISSUE TITLE
[Feature Request] 日志结果直方图横坐标单位可以随则时间缩小而变动

### ISSUE THREAD

**Issue by laojianzi** [clickvisual/clickvisual#623]
## 当前效果

**操作步骤：通过相对时间查询，然后一直通过点击柱状图来缩小时间范围，直到最小**

![image](https://user-images.githubusercontent.com/42930263/189858576-5b80c2a7-7e45-48fa-913d-0a7d0b719b72.png)
![image](https://user-images.githubusercontent.com/42930263/189858874-6ae61d8b-5cd1-46df-892c-f0da6af8e96f.png)
![image](https://user-images.githubusercontent.com/42930263/189858925-81b00be7-ee44-4423-8555-4178a51741a1.png)

## 预期效果

如果将`“一直点击直方图的柱状来缩小时间范围，直到最小”`时的时间条件拷贝出来，重新开一个窗口来输入自定义时间进行查询，得到的横坐标单位会和`“一直点击直方图的柱状来缩小时间范围，直到最小”`的横坐标单位不同

![image](https://user-images.githubusercontent.com/42930263/189862000-41922390-2860-43c2-b3f2-6a8bffa0ddcb.png)

希望可以做到在点击直方图缩小时间范围的时候，横坐标单位也可以更新，有时候一排柱状图都是同一天，我需要通过鼠标聚焦弹出的气泡提示才能得到比较准确的时间点

**Comment by qianque7** [comment]
https://github.com/clickvisual/clickvisual/pull/626/commits/29a025846edc8b44d50158f919b4d15f70bd0f0f

**Comment by kl7sn** [comment]
https://github.com/clickvisual/clickvisual/releases/tag/v0.4.2-rc3 中进行了优化。
