### ISSUE TITLE
[Feature Request] 告警支持多表

### ISSUE THREAD

**Issue by laojianzi** [clickvisual/clickvisual#624]
demo: 
1. stdout
2. error

如果我想要在这两个 table 都检查是否存在 panic 日志，如果有则告警

## 实际效果
![image](https://user-images.githubusercontent.com/42930263/190111438-a261bc68-cdab-42fe-b460-84c4459e29de.png)

我需要创建两个告警来满足，而且表越多我需要创建的告警就越多

## 预期效果
当我需要在一个告警规则使用多张日志表都检查的时候，可以只创建一个日志告警来控制指标

**Comment by qianque7** [comment]
https://github.com/clickvisual/clickvisual/pull/680
