### ISSUE TITLE
新增告警会报错 Syntax error: failed at position 22 (end of query): ;. Expected identifier

### ISSUE THREAD

**Issue by xg0719** [clickvisual/clickvisual#641]
测试版本： v0.4.2-rc2
错误：alarm create failed 02: code: 62, message: Syntax error: failed at position 22 (end of query): ;. Expected identifier

![image](https://user-images.githubusercontent.com/23369777/191957234-45a6972c-68b1-43f9-9ce6-5686a1a2599a.png)

**Comment by kl7sn** [comment]
使用 v0.4.2-rc2 没有复现这个问题，可以提供下报错日志： clickvisual.log ，我这边再进一步排查。


<img width="579" alt="image" src="https://user-images.githubusercontent.com/2037801/192186651-86efc675-a0ab-47e7-afc3-c72aa0c7df87.png">

**Comment by xg0719** [comment]
> 使用 v0.4.2-rc2 没有复现这个问题，可以提供下报错日志： clickvisual.log ，我这边再进一步排查。
> 
> <img alt="image" width="579" src="https://user-images.githubusercontent.com/2037801/192186651-86efc675-a0ab-47e7-afc3-c72aa0c7df87.png">

{"lv":"debug","ts":1663934983,"msg":"pmsplugin","g3s":[["user__1","role__root"," "," "," "," "]]}
{"lv":"info","ts":1663934983,"msg":"Permission ==> isRootUser","reqPms":{"userId":1,"objectType":"instance","objectIdx":"1","subResource":"alarm","acts":["edit"],"domainType":"BaseTable","domainId":"9"}}
{"lv":"debug","ts":1663934984,"msg":"AlertViewGen","viewSQL":"CREATE MATERIALIZED VIEW system.query_log_6420e61d_59da_4641_8e11_6ce7799c2b5a_0 TO metrics.samples AS\nSELECT\n  toDate(event_time) as date,\n  'clickvisual_alert_metrics' as name,\n  array('uuid=6420e61d-59da-4641-8e11-6ce7799c2b5a') as tags,\n  toFloat64(count(*)) as val,\n  event_time as ts,\n  toDateTime(event_time) as updated\nFROM system.query_log\nWHERE client_hostname='xg' GROUP BY event_time;","viewTableName":"system.query_log_6420e61d_59da_4641_8e11_6ce7799c2b5a_0"}
{"lv":"error","ts":1663934984,"msg":"alarm","step":"alarm create failed 07","viewTableName":"","viewSQL":"","err":"code: 62, message: Syntax error: failed at position 22 (end of query): ;. Expected identifier"}
{"lv":"warn","ts":1663934984,"msg":"biz warning","value":"alarm create failed 02: code: 62, message: Syntax error: failed at position 22 (end of query): ;. Expected identifier","value":null,"tid":"085359d6f9ed7a8860a29b8474213962"}

**Comment by kl7sn** [comment]
代码里面确实有问题，有个报错没有返回，我稍后进行修复。

目前解决方式可以，直接到 clickhouse 里面执行这个试试，看下报错，然后针对性解决。
我推测是  metrics.samples 有问题
```
CREATE MATERIALIZED VIEW system.query_log_6420e61d_59da_4641_8e11_6ce7799c2b5a_0 TO metrics.samples AS
SELECT
 toDate(event_time) as date,
 'clickvisual_alert_metrics' as name,
 array('uuid=6420e61d-59da-4641-8e11-6ce7799c2b5a') as tags,
 toFloat64(count(*)) as val,
 event_time as ts,
 toDateTime(event_time) as updated
 FROM system.query_log
WHERE client_hostname='xg' GROUP BY event_time;
```

**Comment by xg0719** [comment]
> 代码里面确实有问题，有个报错没有返回，我稍后进行修复。
> 
> 目前解决方式可以，直接到 clickhouse 里面执行这个试试，看下报错，然后针对性解决。 我推测是 metrics.samples 有问题
> 
> ```
> CREATE MATERIALIZED VIEW system.query_log_6420e61d_59da_4641_8e11_6ce7799c2b5a_0 TO metrics.samples AS
> SELECT
>  toDate(event_time) as date,
>  'clickvisual_alert_metrics' as name,
>  array('uuid=6420e61d-59da-4641-8e11-6ce7799c2b5a') as tags,
>  toFloat64(count(*)) as val,
>  event_time as ts,
>  toDateTime(event_time) as updated
>  FROM system.query_log
> WHERE client_hostname='xg' GROUP BY event_time;
> ```

**Comment by xg0719** [comment]
已经测试过， 直接到 clickhouse 里面执行上面的sql语句，确实能执行;
但是手动执行成功了也没法创建告警，辛苦大佬们优化下

**Comment by kl7sn** [comment]
这个报错原因是 drop 的时候原表名为空导致的，最近新增的多条件告警代码产生的 BUG。
相关修复 https://github.com/clickvisual/clickvisual/pull/656
