### ISSUE TITLE
rancher集群添加失败

### ISSUE THREAD

**Issue by Lionzj** [clickvisual/clickvisual#647]
添加基于rancher创建的k8s集群失败，看了下日志大概是因为证书的问题，请问如何添加自签证书的k8s集群？有没有跳过验证的方法？

W0927 08:34:52.364791  304277 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1.Deployment: Get "https://10.1.97.50/k8s/clusters/c-nrglh/apis/apps/v1/deployments?limit=500&resourceVersion=0": x509: certificate signed by unknown authority
E0927 08:34:52.364995  304277 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1.Deployment: failed to list *v1.Deployment: Get "https://10.1.97.50/k8s/clusters/c-nrglh/apis/apps/v1/deployments?limit=500&resourceVersion=0": x509: certificate signed by unknown authority
W0927 08:34:53.749217  304277 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1.Namespace: Get "https://10.1.97.51:6443/api/v1/namespaces?limit=500&resourceVersion=0": x509: certificate signed by unknown authority
E0927 08:34:53.749319  304277 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1.Namespace: failed to list *v1.Namespace: Get "https://10.1.97.51:6443/api/v1/namespaces?limit=500&resourceVersion=0": x509: certificate signed by unknown authority
W0927 08:34:56.793869  304277 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1.Pod: Get "https://10.1.97.50/k8s/clusters/c-nrglh/api/v1/pods?limit=500&resourceVersion=0": x509: certificate signed by unknown authority
E0927 08:34:56.793988  304277 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://10.1.97.50/k8s/clusters/c-nrglh/api/v1/pods?limit=500&resourceVersion=0": x509: certificate signed by unknown authority
W0927 08:34:57.437284  304277 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1.Service: Get "https://10.1.97.51:6443/api/v1/services?limit=500&resourceVersion=0": x509: certificate signed by unknown authority
E0927 08:34:57.437546  304277 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.1.97.51:6443/api/v1/services?limit=500&resourceVersion=0": x509: certificate signed by unknown authority
W0927 08:34:59.780796  304277 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1.Node: Get "https://10.1.97.50/k8s/clusters/c-nrglh/api/v1/nodes?limit=500&resourceVersion=0": x509: certificate signed by unknown authority
E0927 08:34:59.780912  304277 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://10.1.97.50/k8s/clusters/c-nrglh/api/v1/nodes?limit=500&resourceVersion=0": x509: certificate signed by unknown authority
W0927 08:35:04.067085  304277 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1.Event: Get "https://10.1.97.50/k8s/clusters/c-nrglh/api/v1/events?limit=500&resourceVersion=0": x509: certificate signed by unknown authority
E0927 08:35:04.067206  304277 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1.Event: failed to list *v1.Event: Get "https://10.1.97.50/k8s/clusters/c-nrglh/api/v1/events?limit=500&resourceVersion=0": x509: certificate signed by unknown authority
W0927 08:35:04.253143  304277 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1.Service: Get "https://10.1.97.50/k8s/clusters/c-nrglh/api/v1/services?limit=500&resourceVersion=0": x509: certificate signed by unknown authority
E0927 08:35:04.253242  304277 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.1.97.50/k8s/clusters/c-nrglh/api/v1/services?limit=500&resourceVersion=0": x509: certificate signed by unknown authority
W0927 08:35:04.922634  304277 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1.Endpoints: Get "https://10.1.97.50/k8s/clusters/c-nrglh/api/v1/endpoints?limit=500&resourceVersion=0": x509: certificate signed by unknown authority
E0927 08:35:04.922828  304277 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get "https://10.1.97.50/k8s/clusters/c-nrglh/api/v1/endpoints?limit=500&resourceVersion=0": x509: certificate signed by unknown authority

**Comment by sevennt** [comment]
这个日志是 clickvisual 产生的吧？还是你通过 kubectl 执行安装的时候报出来的？

**Comment by Lionzj** [comment]
clickvisual 日志产生的。
另外我在clickvisual上试了下，能查到集群相关信息。但是看clickvisual 日志还是在一直刷这个报错。。。

**Comment by sevennt** [comment]
嗯，大概了解了，部分权限 clickvisual 暂时是无需使用的，我们先更新一版，稍后你再测试下。

**Comment by sevennt** [comment]
> clickvisual 日志产生的。 另外我在clickvisual上试了下，能查到集群相关信息。但是看clickvisual 日志还是在一直刷这个报错。。。

clickvisual UI 中的『配置』下 Namespace 的 ConfigMap，你那边能访问到么？能修改并发布么？

**Comment by Lionzj** [comment]
> > clickvisual 日志产生的。 另外我在clickvisual上试了下，能查到集群相关信息。但是看clickvisual 日志还是在一直刷这个报错。。。
> 
> clickvisual UI 中的『配置』下 Namespace 的 ConfigMap，你那边能访问到么？能修改并发布么？

昨天用的docker版的折腾了半天没成功，今天换成二进制版的，一开始也不行，后来调着调着看刚才那日志输出以为不行，后来不知道咋的就好了，能看到namespace这些，这会再添加一个简单版本的集群配置又不行了，总之这块感觉挺玄学的。。。

**Comment by Lionzj** [comment]
关于添加集群失败的问题，我自己又仔细检查了一下，可能是之前格式不太严谨导致的，没有添加current-context字段（主要是看留空时灰色示例里面没加这个字段），或者certificate-authority-data有\自动换行之类的。。。这会能正常添加了

**Comment by sevennt** [comment]
那我们先关闭 issue 了，有问题可以再打开。
