### ISSUE TITLE
有没有考虑前端支持像阿里云sls一样的上下文浏览

### ISSUE THREAD

**Issue by w182757427** [clickvisual/clickvisual#658]
公司的研发一致认为阿里云sls的上下文浏览还是比较重要的，使用上下文浏览查看日志非常的方便、快捷、易读，不知大佬们有没有考虑支持此功能。

**Comment by kl7sn** [comment]
目前通过特定字段过滤，例如 pod name，获取按照日志打印时间顺序的日志列表，是否满足需求。

**Comment by w182757427** [comment]
貌似新增日志库的时候时间字段只支持到DateTime64(3)吧，日志量非常大的时候毫秒已经不够用了，如果能支持到DateTime64(9)或许可以

**Comment by w182757427** [comment]
![QQ图片20221008140233](https://user-images.githubusercontent.com/59718599/194691814-cdb3837b-2cc2-472c-a87b-f464958023d0.png)

我按照文档中的建表语句创建本地表，其中使用了_time_second_ DateTime, _time_nanosecond_ DateTime64(9, 'Asia/Shanghai'), 这两个字段，如你所看到的，时间解析字段只能选择_time_second_
