### ISSUE TITLE
能否支持部署在域名子路径？

### ISSUE THREAD

**Issue by shushenghong** [clickvisual/clickvisual#665]
譬如部署在 https://xxx.com/clickvisual/...
是否一定要部署在 https://xxx.com才行？

**Comment by kl7sn** [comment]
参考这个文档：https://clickvisual.gocn.vip/clickvisual/03funcintro/system-settings.html#_3-%E5%AD%90%E8%B7%AF%E5%BE%84%E9%85%8D%E7%BD%AE

**Comment by shushenghong** [comment]
🐂
