### ISSUE TITLE
query for data type Array(String)

### ISSUE THREAD

**Issue by manfrid** [clickvisual/clickvisual#674]
data type Array(String).
how to query ?

**Comment by kl7sn** [comment]
The input box section uses ClickHouse native syntax, u can query by referring to the official documentation.

https://clickhouse.com/docs/en/sql-reference/functions/array-functions/

**Comment by sevennt** [comment]
> The input box section uses ClickHouse native syntax, u can query by referring to the official documentation.
> 
> https://clickhouse.com/docs/en/sql-reference/functions/array-functions/

@manfrid Have you solve your problem ?

**Comment by manfrid** [comment]
I have not solve my problem.

my query sql is below, it works when i use sql command.(object_ids Array(String))
select * from table1 where has(object_ids, '001') limit 10;

but when i use clickvisual,  the query input with "has(object_ids, '001)", warning messages popup
<img width="387" alt="image" src="https://user-images.githubusercontent.com/4531962/195818784-3a94428c-747c-4ca0-bc08-45673375ef63.png">

>

**Comment by kl7sn** [comment]
在 https://github.com/clickvisual/clickvisual/releases/tag/v0.4.3-rc3 中完成了修复。
