### ISSUE TITLE
当数据库无法连接时，切换到分析时页面报Something went wrong.错误

### ISSUE THREAD

**Issue by FengZh61** [clickvisual/clickvisual#677]
版本：[v0.4.3-rc2]
场景复现
clickhouse实例未启动，clickvisual无法连接到实例，然后点分析，实时业务，然后页面就会报错。
![Dingtalk_20221012145239](https://user-images.githubusercontent.com/98309003/195271170-4b6643a9-5d8a-4640-a7ce-331ba976f0ed.jpg)

{"data":{"code":1,"msg":"Instantiate","data":"dial tcp 192.168.154.129:9000: i/o timeout"}}
点击其他页面没有变化，F5刷新后回复正常，再去点击分析，同样还是报错。

我又试着添加新的可以连接的数据源，也是同样的效果。

{"lv":"error","ts":1665557709,"msg":"bizError","value":"instance info error","error":"instance id: 1: record not found","errorVerbose":"record not found\ninstance id: 1\ngithub.com/clickvisual/clickvisual/api/pkg/model/db.InstanceInfo\n\t/home/runner/work/clickvisual/clickvisual/api/pkg/model/db/base.go:385\ngithub.com/clickvisual/clickvisual/api/internal/api/apiv1/bigdata.InstanceDatabaseList\n\t/home/runner/work/clickvisual/clickvisual/api/internal/api/apiv1/bigdata/instance.go:33\ngithub.com/clickvisual/clickvisual/api/pkg/component/core.Handle.func1\n\t/home/runner/work/clickvisual/clickvisual/api/pkg/component/core/core.go:23\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/clickvisual/clickvisual/api/internal/middlewares.AuthChecker.func1\n\t/home/runner/work/clickvisual/clickvisual/api/internal/middlewares/auth.go:45\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/gin-contrib/sessions.Sessions.func1\n\t/home/runner/go/pkg/mod/github.com/gin-contrib/sessions@v0.0.5/sessions.go:54\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/gotomicro/ego/server/egin.traceServerInterceptor.func1\n\t/home/runner/go/pkg/mod/github.com/gotomicro/ego@v1.1.5/server/egin/interceptor.go:331\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/gotomicro/ego/server/egin.metricServerInterceptor.func1\n\t/home/runner/go/pkg/mod/github.com/gotomicro/ego@v1.1.5/server/egin/interceptor.go:303\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/gotomicro/ego/server/egin.(*Container).defaultServerInterceptor.func1\n\t/home/runner/go/pkg/mod/github.com/gotomicro/ego@v1.1.5/server/egin/interceptor.go:227\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/RaMin0/gin-health-check.New.func1\n\t/home/runner/go/pkg/mod/github.com/!ra!min0/gin-health-check@v0.0.0-20180807004848-a677317b3f01/healthcheck.go:61\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:616\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:572\nnet/http.serverHandler.ServeHTTP\n\t/opt/hostedtoolcache/go/1.18.6/x64/src/net/http/server.go:2916\nnet/http.(*conn).serve\n\t/opt/hostedtoolcache/go/1.18.6/x64/src/net/http/server.go:1966\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/asm_amd64.s:1571","tid":"9bb565c92cfa9d18308a704cd33b3161"}

这是报错日志。

**Comment by FengZh61** [comment]
![image](https://user-images.githubusercontent.com/98309003/195273818-14f9ecea-1a7f-469f-ab20-3cefa6e01413.png)

king是我新添加一个实例，mydev是我原来的实例，就是换了个IP，king实例我没有添加任何数据库，他怎么也识别出来了呢？king中的dnslog数据库我收到删除的，原来跟mydev是一样的。

**Comment by kl7sn** [comment]
在 https://github.com/clickvisual/clickvisual/releases/tag/v0.4.3-rc3 中完成了修复。
