### ISSUE TITLE
we need wechat alarm，please

### ISSUE THREAD

**Issue by tangwei0928** [clickvisual/clickvisual#702]
we need wechat alarm，please！

**Comment by kl7sn** [comment]
@tangwei0928 你们是不是已经自己实现了功能。

**Comment by tangwei0928** [comment]
是的，后来我们是直接在代码里强制推送企业微信，没在页面上改动东西，不是走的新增渠道。

>

**Comment by kl7sn** [comment]
那我就关闭这个 issue 了，有兴趣的话可以照这个文档开发
https://clickvisual.gocn.vip/clickvisual/06join/alert-push-channel.html#%E5%90%8E%E7%AB%AF%E5%BC%80%E5%8F%91 

可以提交 PR 兼容后面的版本

**Comment by pigcsy** [comment]
wecom robot push #724
