### ISSUE TITLE
[Feature Request] 日志告警的 prometheus 配置支持 Operator/CRD

### ISSUE THREAD

**Issue by laojianzi** [clickvisual/clickvisual#707]
https://github.com/prometheus-operator/prometheus-operator#customresourcedefinitions

为什么要使用 operator？
1. 大多数生产环境应该运维会推荐优先采用 operator，因为他们管理起来比较方便
2. k8s configmap 限制 1M

**Comment by kl7sn** [comment]
目前我这边需要先抽象下告警流程对象，再增加这个支持。
