### ISSUE TITLE
前端查询时候加载比较慢，api/v1/tables/${tableId}/logs和api/v1/tables/${tableId}/charts 很慢

### ISSUE THREAD

**Issue by xg0719** [clickvisual/clickvisual#738]
如下图所示，前端查询 logs 和 charts 占用很多时间，导致使用体验不太好，数据量大的时候愈发明显;
建议优化下查询方式，提高此处速度
![image](https://user-images.githubusercontent.com/23369777/200309702-6ef6f1e6-5640-4d09-9af6-c3c7b45f3afe.png)

**Comment by kl7sn** [comment]
删除了并发查询逻辑，该用 group by 方式。
https://github.com/clickvisual/clickvisual/pull/741
