### ISSUE TITLE
日志分析字段不完整

### ISSUE THREAD

**Issue by rrsunhome** [clickvisual/clickvisual#778]
发生了什么？
描述
 日志查询首页，分析字段列表不包含 Int 类型字
![image](https://user-images.githubusercontent.com/34878555/202890128-c085f4ec-413e-4c50-bf06-309fb39599b8.png)

重现步骤
新增日志库->创建方式（接入日志库）

预期结果
分析字段列表应该包含所有字段列表

**Comment by kl7sn** [comment]
@rrsunhome https://github.com/clickvisual/clickvisual/commit/50b65e6a6a7cd0ea518b97a514737f84279d4a10 已完成了相关修复，本周五进行版本迭代发布。
