### ISSUE TITLE
[Feature Request] 查询结果后直接选择查看前后数据

### ISSUE THREAD

**Issue by duffiye** [clickvisual/clickvisual#780]
根据查询条件得到结果后可以选择查看这个时间前后的数据。

**Comment by duffiye** [comment]
> 类似日志上下文的功能？

是的

**Comment by kl7sn** [comment]
暂时没有计划开发类似功能，参考以下 issues
- https://github.com/clickvisual/clickvisual/issues/658
- https://github.com/clickvisual/clickvisual/issues/506
