### ISSUE TITLE
好像无法选择datetime64数据类型

### ISSUE THREAD

**Issue by w38351479** [clickvisual/clickvisual#789]
好像无法选择datetime64，数据类型。如果选择datetime，后面查询出现
SELECT * FROM `logs_data`.`nginx_error_all` WHERE log_time >= toDateTime(1669284478) AND log_time < toDateTime(1669285378) AND 。。。。。

![QQ图片20221124183835](https://user-images.githubusercontent.com/20940470/203763720-0c9f1a29-35a1-4c57-a237-c932e994de83.png)

**Comment by w38351479** [comment]
clickhouse版本 22.8.6.71

**Comment by kl7sn** [comment]
需要发下具体的数据表结构，目前时间字段筛选使用的是 like Int 和 like DateTime。

**Comment by w38351479** [comment]
`CREATE TABLE logs_data.messages_local ON CLUSTER 'cluster01' (
    log_uuid UUID default generateUUIDv4(),
    project_group String,
    host_id String,
    env String,
    log_time DateTime64(3, 'Asia/Shanghai'),
    log_content String,
    create_time DateTime64(3, 'Asia/Shanghai') default now(),
    INDEX index1 (project_group, log_time, env) TYPE set(100) GRANULARITY 4
) ENGINE =......`

**Comment by w38351479** [comment]
CREATE TABLE logs_data.messages_local ON CLUSTER 'cluster01' (
    log_uuid UUID default generateUUIDv4(),
    project_group String,
    host_id String,
    env String,
    log_time DateTime64(3, 'Asia/Shanghai'),
    log_content String,
    create_time DateTime64(3, 'Asia/Shanghai') default now(),
    INDEX index1 (project_group, log_time, env) TYPE set(100) GRANULARITY 4
) ENGINE =......
