### ISSUE TITLE
前端页面样式建议

### ISSUE THREAD

**Issue by w38351479** [clickvisual/clickvisual#793]
个人觉得日志可视部分DIV比较小，觉得可以缩紧DIV直接的间隔，使内容更加紧凑
![image](https://user-images.githubusercontent.com/20940470/203940977-13d3cfc4-e3c2-466a-9b93-dd42a3357a76.png)
![image](https://user-images.githubusercontent.com/20940470/203941220-4e8b9754-e74d-4b48-97cd-6757efbf9999.png)

下面这里能动态调整更加完美，麻烦就直接加宽也行
![image](https://user-images.githubusercontent.com/20940470/203941462-70a044a3-1885-4513-8fcd-ffa28ead5ae0.png)

**Comment by kl7sn** [comment]
@qianque7 看看
