### ISSUE TITLE
第一次启动就一直卡着，是什么情况？

### ISSUE THREAD

**Issue by huoarter** [clickvisual/clickvisual#795]
![image](https://user-images.githubusercontent.com/17919074/203965013-19c5b9b0-5c04-4478-bf2d-41721339d468.png)
默认配置，只修改了mysql和redis地址，创建了clickvisual数据库。 
版本： clickvisual-v0.4.4-rc4

**Comment by kl7sn** [comment]
没有报错的话是没有其他日志打印的，可以直接访问。

**Comment by huoarter** [comment]
忘记说了另外的问题：访问localhost:19011时候没有webui的页面，只有api显示的页面,是访问的不对吗？

**Comment by huoarter** [comment]
> 没有报错的话是没有其他日志打印的，可以直接访问。

我知道了，我访问localhost:19011应该是后端api，ui应该访问localhost:19001.
感谢。
另外提出一个文档里面的错误，启动命令：./clickvisual -config config/default.toml  应该是--config
