### ISSUE TITLE
两次搜索查询出来的结果不一致

### ISSUE THREAD

**Issue by zy14** [clickvisual/clickvisual#801]
![image](https://user-images.githubusercontent.com/13267004/204763543-6158746d-211f-4d90-9dd3-806e96b2aa4f.png)
![image](https://user-images.githubusercontent.com/13267004/204763605-2ce3541d-8da1-43b9-8329-c73df97b7c8a.png)
两次搜索查询出来的结果不一致
版本 0.4.4
clickhouse版本 22.3.10.22

**Comment by qianque7** [comment]
会不会是因为相对时间   两次搜索时间段不一致导致的总条数不一致

**Comment by kl7sn** [comment]
接入日志库还是用 clickvisual 创建的日志库。

**Comment by zy14** [comment]
接入日志库

**Comment by kl7sn** [comment]
应该是集群吧，接入了其中一个分片，会有这个情况。

**Comment by zy14** [comment]
嗯 是的 集群

**Comment by kl7sn** [comment]
找到问题原因了吗？之前出现类似的现象是由于接入时选择的是分片表。
