### ISSUE TITLE
日志查询列表显示无效日期

### ISSUE THREAD

**Issue by rrsunhome** [clickvisual/clickvisual#803]
## 问题
日志查询列表显示无效日期
![image](https://user-images.githubusercontent.com/34878555/205004999-bbcb4eeb-d55a-4e2a-8419-ec213522e075.png)

## 版本
0.4.4

## 复现步骤
新增日志库-> 接入日志库

**Comment by rrsunhome** [comment]
日志字段 timestamp DateTime64(3)

**Comment by rrsunhome** [comment]
你好，预计什么时间修复该问题，我这边升级的目的是想应用告警模块

**Comment by kl7sn** [comment]
修复已合并，明天发布 rc 版本。
