### ISSUE TITLE
[FEATURE]: Get the alertmanager url configured in any way

### ISSUE THREAD

**Issue by laojianzi** [clickvisual/clickvisual#806]
**Concisely describe the proposed feature**

Get the alertmanager url configured in any way
Not limited to `targets`

**Describe the solution you'd like (if any)**
A clear and concise description of what you want to achieve and implement. 

Use the API `/v1/alertmanagers` to get

e.g:
```json
{
    "status": "success",
    "data": {
        "activeAlertmanagers": [
            {
                "url": "http://1.2.3.4:9093/api/v2/alerts"
            }
        ],
        "droppedAlertmanagers": [
            {
                "url": "http://11.22.33.44:9093/api/v2/alerts"
            },
        ]
    }
}
```

**Additional comments**

**Comment by kl7sn** [comment]
这个是要获取告警配置里面全部的 prometheus 依赖的 alertmanager 的状态列表吗？

**Comment by laojianzi** [comment]
@kl7sn 主要目的是想要获取那些不是通过 `targets` 定义的配置，比如 `relabel_configs `

**Comment by kl7sn** [comment]
修复了，原因是在读取配置之前测试了 reload 接口，导致 alertmanager 读取到空数据，调整了检测顺序。
