### ISSUE TITLE
收藏的sql查询语句，界面没有地方调用[BUG]:

### ISSUE THREAD

**Issue by w38351479** [clickvisual/clickvisual#811]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.
查询的sql收藏后，看到已经插入到mysql数据库中，但是界面没有地方调用。

**ClickVisual Running Environment**
Please provide the following information:

- ClickVisual version:
0.4.4
- ClickVisual.LOG:

**Comment by kl7sn** [comment]
<img width="953" alt="image" src="https://user-images.githubusercontent.com/2037801/205541833-c66d8323-f65c-4924-803a-b67662e7fbda.png">
目前会在输入框中优先匹配收藏语句，后续我们增加一个点击入口提供手动筛选。
