### ISSUE TITLE
[BUG]:分布表json类型问题

### ISSUE THREAD

**Issue by onine007** [clickvisual/clickvisual#812]
**Describe the bug**
 数据源中含有json类型字段的表; 配置本地表,没问题.  配置分布表,程序会奔溃,报错.最后503

**ClickVisual Running Environment**

- ClickVisual version:   v0.4.3 和 0.4.5-rc1

- ClickVisual.LOG: 
- 
- {"data":"<html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body>\r\n<center><h1>503 Service Temporarily Unavailable</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n\r\n\r\n\r\n\r\n\r\n\r\n","response":{"headers":[{"key":"content-length","val":"592"},{"key":"content-type","val":"text/html"},{"key":"date","val":"Mon, 05 Dec 2022 01:43:38 GMT"}],"ok":false,"redirected":false,"status":503,"statusText":"","type":"basic","url":"https://clickvisual.admin.internal.taqu.cn/api/v1/tables/14"},"request":{"url":"/api/v1/tables/14"}}

**Comment by kl7sn** [comment]
方便提供下【分布表】的建表语句吗？

**Comment by onine007** [comment]
CREATE TABLE tq_log.ods_client_report_log_success_all
(
    `token` String COMMENT '用户唯一标识' CODEC(ZSTD(1)),
    `version` LowCardinality(String) COMMENT 'app 版本号',
    `appcode` LowCardinality(String) COMMENT '应用标识',
    `cloned` LowCardinality(String) COMMENT '应用分身ID',
    `network` LowCardinality(String) COMMENT '网络情况',
    `ip` String COMMENT 'ip地址' CODEC(ZSTD(1)),
    `platform` LowCardinality(String) COMMENT '手机平台 ',
    `channel` LowCardinality(String) COMMENT '渠道',
    `city` LowCardinality(String) COMMENT '用户当前定位城市ID',
    `model` LowCardinality(String) COMMENT '手机型号',
    `track_id` Int64 COMMENT '事件行为唯一标识' CODEC(T64),
    `event_time` DateTime COMMENT ' 事件时间',
    `event_id` LowCardinality(String) COMMENT '事件ID',
    `content` Object('json') COMMENT '事件属性',
    `ot` LowCardinality(String) COMMENT '网络服务商',
    `platform_ver` LowCardinality(String) COMMENT '手机系统版本',
    `session_id` Int64 COMMENT '会话' CODEC(T64),
    `is_front` LowCardinality(String) COMMENT ' 是、否',
    `seq` LowCardinality(UInt32) COMMENT '顺序',
    `_timestamp` DateTime COMMENT '上报时间' CODEC(LZ4HC(5)),
    `content_str` String ALIAS toJSONString(content),
    `content_type` String ALIAS toTypeName(content)
)
ENGINE = Distributed('default', 'tq_log', 'ods_client_report_log_success_local', rand())
