### ISSUE TITLE
[BUG]: 查询出来的结果和展示的不一样

### ISSUE THREAD

**Issue by onine007** [clickvisual/clickvisual#813]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.
![iOrLp7D58i](https://user-images.githubusercontent.com/24770345/205552359-b2708351-8253-4a92-8429-940585918524.jpg)

clickhouse 存的是过滤条件的那个,  类型是UInt64 ;

**ClickVisual Running Environment**

- ClickVisual version:
- 0.4.5-rc1 

- ClickVisual.LOG:

**Comment by kl7sn** [comment]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/2037801/205614973-ca592bcd-c581-49d5-a365-ab545be14fda.png">
点击这个按钮，可以看到具体的查询语句。用该语句直接查询 ClickHouse 在和 CV 查询结果比较下差异。
