### ISSUE TITLE
[FEATURE]: Filter 日志的时候字段严格按照类型写入value

### ISSUE THREAD

**Issue by hantmac** [clickvisual/clickvisual#836]
**Concisely describe the proposed feature**
目前 Filter 字段的时候，value 都是按照 String 写入的：
<img width="835" alt="image" src="https://user-images.githubusercontent.com/7600925/207807817-70b339f7-1881-457b-972b-afab4d51fa27.png">

<img width="346" alt="image" src="https://user-images.githubusercontent.com/7600925/207807579-9ef954ba-f5f7-4b48-ba96-33c6c0136c0d.png">
期望添加 Filter 字段的时候能够严格按照类型写入 Value

**Comment by kl7sn** [comment]
@qianque7 补充说明 https://github.com/clickvisual/clickvisual/discussions/834#discussioncomment-4407730

**Comment by hantmac** [comment]
貌似这个问题还木有解决🤔
<img width="1526" alt="image" src="https://user-images.githubusercontent.com/7600925/210349037-999b9bbb-efe3-4b0e-a6a7-0a46a5a48a0c.png">
