### ISSUE TITLE
[QUESTION]: 添加告警后无法正常告警

### ISSUE THREAD

**Issue by mcy567** [clickvisual/clickvisual#857]
用docker-compose.yml部署后，显示这个报错：

![image](https://user-images.githubusercontent.com/22673808/210482772-c45f39ed-5cf4-414b-a219-e12bc35b396a.png)

看官方文档用这种方式解决：

![image](https://user-images.githubusercontent.com/22673808/210483001-43221bd3-a3a8-4531-a84b-aa6c27794c8e.png)

但是实际部署后，没有这个配置项：

![image](https://user-images.githubusercontent.com/22673808/210483044-8a3fb48a-e7d0-41b9-9694-68136d910bf0.png)

**Comment by kl7sn** [comment]
菜单文件没有更新，可以拉取最新的代码试试。

**Comment by mcy567** [comment]
> 菜单文件没有更新，可以拉取最新的代码试试。

可以创建了，不过现实了其他的报错：
![image](https://user-images.githubusercontent.com/22673808/210569453-aaa65b45-5be5-4c4c-960b-2543a6351fe7.png)

**Comment by mcy567** [comment]
搞定了，需要点击Options，填写规则的路径：

![image](https://user-images.githubusercontent.com/22673808/210698733-957557be-fca7-4405-b150-e61d4ca7ca58.png)

参考了 https://github.com/clickvisual/clickvisual/issues/622 ，这个文件路径是clickvisual容器下存放Prometheus规则的路径，当前版本clickvisual容器里面路径是/clickvisual/rules。我理解用户创建告警规则后，首先会在这个目录下生成规则文件，然后再将规则发送到Prometheus容器的/etc/prometheus/rules/下

这个文档里面的内容有一点误导作用，建议修改下：https://clickvisual.gocn.vip/clickvisual/03funcintro/alarm-function-configuration-description.html#%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE

![image](https://user-images.githubusercontent.com/22673808/210698107-4afafb8b-f6a7-4bf0-a599-e016252ecd6a.png)

**Comment by kl7sn** [comment]
我优化下文档，感谢反馈。

**Comment by kl7sn** [comment]
问题关联到 https://github.com/clickvisual/clickvisual/issues/967
