### ISSUE TITLE
[BUG]:字段类型设置为Int16的字段无法做分析，显示暂无数据，改成Int32就正常了。

### ISSUE THREAD

**Issue by starsliao** [clickvisual/clickvisual#865]
status字段类型设置为Int16时，无法做分析，显示暂无数据，改成Int32就正常了。
如图所示：
![图片](https://user-images.githubusercontent.com/3349611/210734707-1311404c-cdbd-4a11-9dce-0505accc2707.png)

**Comment by kl7sn** [comment]
在 https://github.com/clickvisual/clickvisual/releases/tag/v0.4.6-rc1 中完成了修复。
