### ISSUE TITLE
[QUESTION]: 推送报警异常

### ISSUE THREAD

**Issue by rrsunhome** [clickvisual/clickvisual#880]
## 问题
 推送报警异常、推送到飞书异常，什么情况推送报警为否?
![image](https://user-images.githubusercontent.com/34878555/211793875-959cd5f4-d30d-4934-b455-272f2d866d37.png)

**Comment by kl7sn** [comment]
这个地方的显示文本我们优化下，这个否的原因是在告警中重复触发了告警，所以没有进行推送。

**Comment by rrsunhome** [comment]
是因为告警状态为告警中，所以不发送了吗？

**Comment by rrsunhome** [comment]
日志告警链路太长，链路中每增加一个环节整体可用性、触达率都会降低，后续这块会优化吗？就像这个问题，如果要排查为什么没有发出通知、需要排查 clickhouse 源数据、alert manager 、clickvisual 这三个组件是否正常工作

**Comment by kl7sn** [comment]
目前在组件这边有可用性检测，理论上这个没有报错，链路就是正常的。
我这边考虑下是否可以提供快速检测的方案。
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/2037801/215262314-fcebd15d-0cda-467e-89c6-49e141c90584.png">
