### ISSUE TITLE
[DOC]:能否在Docker-Compose 体验中添加链路日志的体验数据呢

### ISSUE THREAD

**Issue by FengZh61** [clickvisual/clickvisual#882]
Please describe any errors, ambiguities, or other improvement opportunities that you can find in the documentation.
https://clickvisual.gocn.vip/zh/clickvisual/01quickstart/experience-clickvisual-with-docker-compose.html
文档中，只有常规日志的体验数据，能否添加一下链路日志的体验数据呢？
RT

**Comment by kl7sn** [comment]
可以，目前在重构日志库创建方式，后续会进行该需求的支持。

**Comment by kl7sn** [comment]
当前问题关联到 #974
