### ISSUE TITLE
[DOC]: 日志展示问题

### ISSUE THREAD

**Issue by pidouzi** [clickvisual/clickvisual#886]
将日志采集解析为json后存入kafka，创建日志库后，日志中只显示了_raw_log_ 原始数据，将数据提取后通过json格式化可以正常解析。创建了7个日志库，其中两个出现了这种问题
![image](https://user-images.githubusercontent.com/50960351/213133520-3bff26c9-bb30-4f6f-abeb-8d4ac2c6c18e.png)
将_raw_log_中的数据解析后为下图
![image](https://user-images.githubusercontent.com/50960351/213134595-0c0b9d43-1436-48b4-b5ba-7bec6caa129e.png)

表结构：
日志表
CREATE TABLE IF NOT EXISTS `logger`.`app_info`
(
  _time_second_ DateTime,
  _time_nanosecond_ DateTime64(9),
  _key String CODEC(ZSTD(1)),
  _raw_log_ String CODEC(ZSTD(1)),
  `_headers.name` Array(String),
  `_headers.value` Array(String),
  INDEX idx_raw_log _raw_log_ TYPE tokenbf_v1(30720, 2, 0) GRANULARITY 1
)
ENGINE = MergeTree
PARTITION BY toYYYYMMDD(_time_second_)
ORDER BY _time_second_
TTL toDateTime(_time_second_) + INTERVAL 30 DAY
SETTINGS index_granularity = 8192;

视图表

CREATE MATERIALIZED VIEW IF NOT EXISTS `logger`.`app_info_view` TO `logger`.`app_info` AS
SELECT
  parseDateTimeBestEffort(JSONExtractString(body, '_time_')) AS _time_second_,
  toDateTime64(parseDateTimeBestEffort(JSONExtractString(body, '_time_')), 9) AS _time_nanosecond_,
  _key AS _key,
  `_headers.name` AS `_headers.name`,`_headers.value` AS `_headers.value`,
  body AS _raw_log_ 
FROM `logger`.`app_info_stream`
WHERE 1=1;

引擎表
CREATE TABLE IF NOT EXISTS `logger`.`app_info_stream`
(
  body String
)
ENGINE = Kafka SETTINGS kafka_broker_list = '192.92', 
kafka_topic_list = 'exter_test', 
kafka_group_name = 'logger_app_info', 
kafka_format = 'JSONAsString', 
kafka_num_consumers = 3,
kafka_skip_broken_messages = 0;

**Comment by kl7sn** [comment]
使用JSONEachRow的方式创建日志库试试，后续版本会移除JSONAsString的流程。

**Comment by pidouzi** [comment]
正在尝试，由于日志不是结构化的，格式化后，将字段填入_log_是json，并不是字符串，目前正在找将json 转成 string的方法

**Comment by kl7sn** [comment]
这边目前也正在支持_log_字段非string的场景

**Comment by pidouzi** [comment]
{"_time_":"2023-01-30T06:19:45.000000Z","_log_":"{\"method\":\"POST\",\"host\":\"baidu.com\",\"url\":\"/list\",\"remote_addr\":\"1.1.1.1\",\"msg\":\"[ error ] [2]DOMDocument::loadHTML(): Tag nouse invalid in Entity, line: 1[/controller/Xss.php:58]\n[ error ] [2]DOMDocument::loadHTML(): Tag nouse invalid in Entity, line: 1[/controller/Xss.php:58]\n[ error ] [2]DOMDocument::loadHTML(): Tag nouse invalid in Entity, line: 1[/controller/Xss.php:58]\n[ error ] [2]DOMDocument::loadHTML(): Tag nouse invalid in Entity, line: 1[/controller/Xss.php:58]\n\"}","_namespace_":"default","_pod_name_":"default-794b9f7bf7-dbjlv","_cluster_":"test","_log_agent_":"fluent-bit-zcnsn","_node_ip_":"192.168.1.6"}

这是我从kafka拿到的数据，使用JSONEachRow进行解析还是只出现了_raw_log_字段，并没有解析_log_字段，是因为换行符的原因吗

**Comment by pidouzi** [comment]
![image](https://user-images.githubusercontent.com/50960351/215403597-443d1045-9359-4ff2-8ce9-80ed6361f825.png)

**Comment by pidouzi** [comment]
测试了下，去掉换行符就正常了

**Comment by pidouzi** [comment]
换行符转义看到数据也是正常的
