### ISSUE TITLE
[BUG]:版本clickvisual-v0.4.6-rc1.tar.gz登录不显示菜单

### ISSUE THREAD

**Issue by flylkng** [clickvisual/clickvisual#901]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.
通过二进制编译安装，初始化数据后登录，不显示菜单
**ClickVisual Running Environment**
Please provide the following information:

- ClickVisual version:
clickvisual-v0.4.6-rc1.tar.gz
- ClickVisual.LOG:

**Comment by kl7sn** [comment]
可以确认下同根目录下是否包含
- rbac.conf
- resource.yaml

![image](https://user-images.githubusercontent.com/2037801/215928786-055acabd-9c4f-4919-8002-4cdb54c3502e.png)
