### ISSUE TITLE
[BUG]: 告警责任人不显示和AT不到指定人

### ISSUE THREAD

**Issue by hedongfang** [clickvisual/clickvisual#914]
告警责任人不显示和AT不到指定人
![image](https://user-images.githubusercontent.com/49864372/216285339-83d1c235-037d-4999-a250-82b9f6871d07.png)
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/49864372/216285362-730a9e1d-38f9-4e80-b721-28f9912a9457.png">
<img width="771" alt="image" src="https://user-images.githubusercontent.com/49864372/216285381-2120c9bb-5072-4f2f-a403-875709d4afd2.png">

**Comment by kl7sn** [comment]
在 https://github.com/clickvisual/clickvisual/releases/tag/v0.4.6-rc4 中完成了修复
