### ISSUE TITLE
[BUG]: 修改用户NickName名称保存后，手机号码被改变

### ISSUE THREAD

**Issue by hedongfang** [clickvisual/clickvisual#918]
错误：用户管理，修改用户NickName名称保存后，手机号码被改变，存入数据库变成”180****5310“
<img width="991" alt="image" src="https://user-images.githubusercontent.com/49864372/216527365-1172c1b4-8222-45f3-9975-ffeb9212efc2.png">

**Comment by kl7sn** [comment]
master 分支完成修复。
