### ISSUE TITLE
mac 10.15.7 amd二进制安装成功之后，启动时一直报错[QUESTION]:

### ISSUE THREAD

**Issue by tiantsl** [clickvisual/clickvisual#920]
mac 10.15.7 amd二进制安装成功之后，启动时一直报错，配置文件中，MySQL和redis配置已做了修改，还是仍然报错,数据库用别的工具可以正常连接成功。程序启动报错如下图:
<img width="1093" alt="216547392-5bf29816-f082-43b0-a99a-8ccc7fb0d202" src="https://user-images.githubusercontent.com/38754898/216548133-57f7ec36-3f38-4222-85c5-1b491befb9c7.png">

**Comment by sevennt** [comment]
看下这个报错提示，确认下数据库的 DSN 是不是配置正确了，看起来像是用户名/密码不对，或者没有访问数据库的权限？

**Comment by tiantsl** [comment]
> 看下这个报错提示，确认下数据库的 DSN 是不是配置正确了，看起来像是用户名/密码不对，或者没有访问数据库的权限？ @tiantsl

已解决，的确是配置的问题，没有相关的配置文档描述，我以为数据库密码是需要单独配置的，密码在dsn中配置即可。。
