### ISSUE TITLE
新增实例时测试连接clickhouse总是提示连接失败

### ISSUE THREAD

**Issue by tiantsl** [clickvisual/clickvisual#923]
使用dbeaver连接clickhouse可以正常连接，新增实例时测试总是通不过
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/38754898/216905459-30fae0db-9e63-456f-a2be-d4e6c55615a9.png">
<img width="791" alt="image" src="https://user-images.githubusercontent.com/38754898/216905960-a8ea8418-f4af-4261-85f1-73c65a6c3cc2.png">

**Comment by kl7sn** [comment]
https://github.com/ClickHouse/clickhouse-go

> clickhouse://username:password@host1:9000,host2:9000/database?dial_timeout=200ms&max_execution_time=60

**Comment by gohonsen** [comment]
把 localhost 换成你 clickhouse 节点的 IP，端口换成 9000 那个端口，协议不一样
