### ISSUE TITLE
现有版本和操作文档截图完全不一样，实现起来有困难，建议更新一下文档

### ISSUE THREAD

**Issue by tiantsl** [clickvisual/clickvisual#925]
尤其是新增日志库这里，表单中的内容不一样，文档上和现在部署打开的下拉选择都不一样，创建方式有三种，每种创建方式的区别和实现方式，缺少文档描述，实现起来感觉糊里糊涂的，有点困难，建议作者有空更新一下文档。
<img width="902" alt="image" src="https://user-images.githubusercontent.com/38754898/217126094-db6723f4-7f07-40bb-b956-5d73cfc6a850.png">
文档中的示例截图
![image](https://user-images.githubusercontent.com/38754898/217126321-464bac10-f211-449c-8907-d8f931da21e1.png)

**Comment by kl7sn** [comment]
目前文档是针对 0.4.5 稳定版本提供的，由于 rc 版本涉及的 0.4.6 版本未完全开发完，因此文档产生了未同步的问题，十分抱歉，这边会尽快优化文档。
