### ISSUE TITLE
[BUG]:告警聚合模式，链接跳转查询错误

### ISSUE THREAD

**Issue by hedongfang** [clickvisual/clickvisual#926]
链接跳转拼接是否有问题。
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/49864372/217708905-972a59a9-0319-43a9-b818-f052fcbe9925.png">

**Comment by qianque7** [comment]
看样子是查询语句中携带了换行符，触发了多行模式，鼠标聚焦在搜索栏可以展示完整的搜索框，需要您这边对比下查询语句的差异，或者贴上脱敏后的url和搜索框内的全部内容，这边尝试能否复现

**Comment by hedongfang** [comment]
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/49864372/217778783-421e4901-5cb1-43a5-9f21-417f9436d055.png">
<img width="833" alt="image" src="https://user-images.githubusercontent.com/49864372/217778908-55ba0f7b-1f73-48e5-8fb8-8dbc070df7d1.png">
