### ISSUE TITLE
[BUG]:  日志查询性能差异大

### ISSUE THREAD

**Issue by rrsunhome** [clickvisual/clickvisual#932]
**Describe the bug**
1. 通过 clickvisual 界面查询 30 天内的数据加上检索条件，执行耗时: 27503ms 
2. 通过 clickvisual  excel 界面查询 30 天内的数据加上检索条件，执行耗时: 1.79 s 

**详细截图如下:**
问题1 
![image](https://user-images.githubusercontent.com/34878555/218911784-bd472a09-06d7-429d-a512-ca0900375864.png)

问题2
![image](https://user-images.githubusercontent.com/34878555/218911860-08174e46-2a01-4a41-8ffe-e40f0c77a291.png)
![image](https://user-images.githubusercontent.com/34878555/218911908-070b7f1f-52dd-4559-893d-a793d13b9eb6.png)

**ClickVisual Running Environment**
 centos7
- ClickVisual version:
v0.4.5-rc1
- ClickVisual.LOG:

**Comment by kl7sn** [comment]
这两个查询逻辑不一样，查询耗时是不同的。

多次查询耗时也是稳定如上情况吗？

**Comment by rrsunhome** [comment]
> 这两个查询逻辑不一样，查询耗时是不同的。
> 
> 多次查询耗时也是稳定如上情况吗？

是的，多次查询耗时相同

两个查询逻辑区别在哪里呢，对使用方来说快速展示出数据即可。另外，查询逻辑部分可以优化吗，针对非隐藏的字段列表选择性查询延迟小一些

**Comment by rrsunhome** [comment]
> > 这两个查询逻辑不一样，查询耗时是不同的。
> > 多次查询耗时也是稳定如上情况吗？
> 
> 是的，多次查询耗时相同
> 
> 两个查询逻辑区别在哪里呢，对使用方来说快速展示出数据即可。另外，查询逻辑部分可以优化吗，针对非隐藏的字段列表选择性查询延迟小一些

两个不同查询逻辑，延时差距太大

**Comment by kl7sn** [comment]
你使用的方式是接入已有日志库吗？

**Comment by sixiaojie** [comment]
使用clickvisual查询在clickhouse实际上是有两个，一个是正常的查询select * ... limit 10，用于展示日志的具体条目. 这里查询速度是很快的。就像你下面自己使用的语句一样。但还有一个是趋势图，一般这里的速度是随着你的数据量而提升的。你的慢应该是在这个地方

**Comment by rrsunhome** [comment]
和趋势图没有关系，我把趋势图开关禁用了，

**Comment by taizilongxu** [comment]
同样的问题

**Comment by hasylu** [comment]
可以关闭直方图，会快一些
