### ISSUE TITLE
[BUG]: 单机clickhouse实例，创建日志库使用ReplicatedMergeTree

### ISSUE THREAD

**Issue by Cerberuxx** [clickvisual/clickvisual#943]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.

**ClickVisual Running Environment**
Please provide the following information:

- ClickVisual version: started by docker compose, image is clickvisual/clickvisual:master

- ClickVisual.LOG: {"lv":"error","ts":1678083205,"msg":"bizError","lname":"clickvisual.log","value":"create failed 01:: error sql is: CREATE TABLE IF NOT EXISTS `accesslog`.`hd_nginx_local` on cluster ''\n(\n`host` String,\n`@metadata` String,\n`message` String,\n`idc` String,\n`nginx-content` String,\n`nginx-zone` String,\n_time_second_ DateTime,\n_time_nanosecond_ DateTime64(9),\n_raw_log_ String CODEC(ZSTD(1)),\n_key String CODEC(ZSTD(1)),\n`_headersname` Array(String),\n`_headersvalue` Array(String),\nINDEX idx_raw_log _raw_log_ TYPE tokenbf_v1(30720, 2, 0) GRANULARITY 1\n)\nENGINE = ReplicatedMergeTree('/clickhouse/tables/accesslog.hd_nginx_local/{shard}', '{replica}')\nPARTITION BY toYYYYMMDD(_time_second_)\nORDER BY _time_second_\nTTL toDateTime(_time_second_) + INTERVAL 1 DAY\nSETTINGS index_granularity = 8192;\n: code: 62, message: No macro 'shard' in config while processing substitutions in '/clickhouse/tables/accesslog.hd_nginx_local/{shard}' at '45' or macro is not supported here","error":"create failed 01:: error sql is: CREATE TABLE IF NOT EXISTS `accesslog`.`hd_nginx_local` on cluster ''\n(\n`host` String,\n`@metadata` String,\n`message` String,\n`idc` String,\n`nginx-content` String,\n`nginx-zone` String,\n_time_second_ DateTime,\n_time_nanosecond_ DateTime64(9),\n_raw_log_ String CODEC(ZSTD(1)),\n_key String CODEC(ZSTD(1)),\n`_headersname` Array(String),\n`_headersvalue` Array(String),\nINDEX idx_raw_log _raw_log_ TYPE tokenbf_v1(30720, 2, 0) GRANULARITY 1\n)\nENGINE = ReplicatedMergeTree('/clickhouse/tables/accesslog.hd_nginx_local/{shard}', '{replica}')\nPARTITION BY toYYYYMMDD(_time_second_)\nORDER BY _time_second_\nTTL toDateTime(_time_second_) + INTERVAL 1 DAY\nSETTINGS index_granularity = 8192;\n: code: 62, message: No macro 'shard' in config while processing substitutions in '/clickhouse/tables/accesslog.hd_nginx_local/{shard}' at '45' or macro is not supported here","errorVerbose":"code: 62, message: No macro 'shard' in config while processing substitutions in '/clickhouse/tables/accesslog.hd_nginx_local/{shard}' at '45' or macro is not supported here\nerror sql is: CREATE TABLE IF NOT EXISTS `accesslog`.`hd_nginx_local` on cluster ''\n(\n`host` String,\n`@metadata` String,\n`message` String,\n`idc` String,\n`nginx-content` String,\n`nginx-zone` String,\n_time_second_ DateTime,\n_time_nanosecond_ DateTime64(9),\n_raw_log_ String CODEC(ZSTD(1)),\n_key String CODEC(ZSTD(1)),\n`_headersname` Array(String),\n`_headersvalue` Array(String),\nINDEX idx_raw_log _raw_log_ TYPE tokenbf_v1(30720, 2, 0) GRANULARITY 1\n)\nENGINE = ReplicatedMergeTree('/clickhouse/tables/accesslog.hd_nginx_local/{shard}', '{replica}')\nPARTITION BY toYYYYMMDD(_time_second_)\nORDER BY _time_second_\nTTL toDateTime(_time_second_) + INTERVAL 1 DAY\nSETTINGS index_granularity = 8192;\n\ngithub.com/clickvisual/clickvisual/api/core/common.Exec\n\t/clickvisual/api/core/common/exec.go:15\ngithub.com/clickvisual/clickvisual/api/core/storer/clickhouse.(*Storer).Create\n\t/clickvisual/api/core/storer/clickhouse/clickhouse.go:63\ngithub.com/clickvisual/clickvisual/api/internal/service/inquiry.(*ClickHouseX).CreateStorage\n\t/clickvisual/api/internal/service/inquiry/clickhouse.go:1005\ngithub.com/clickvisual/clickvisual/api/internal/service.StorageCreate\n\t/clickvisual/api/internal/service/table.go:83\ngithub.com/clickvisual/clickvisual/api/internal/api/apiv2/storage.Create\n\t/clickvisual/api/internal/api/apiv2/storage/storage.go:79\ngithub.com/clickvisual/clickvisual/api/pkg/component/core.Handle.func1\n\t/clickvisual/api/pkg/component/core/core.go:23\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/clickvisual/clickvisual/api/internal/middlewares.isNotLogin\n\t/clickvisual/api/internal/middlewares/auth.go:73\ngithub.com/clickvisual/clickvisual/api/internal/middlewares.AuthChecker.func1\n\t/clickvisual/api/internal/middlewares/auth.go:24\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/gin-contrib/sessions.Sessions.func1\n\t/go/pkg/mod/github.com/gin-contrib/sessions@v0.0.5/sessions.go:54\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/gotomicro/ego/server/egin.traceServerInterceptor.func1\n\t/go/pkg/mod/github.com/gotomicro/ego@v1.1.5/server/egin/interceptor.go:331\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/gotomicro/ego/server/egin.metricServerInterceptor.func1\n\t/go/pkg/mod/github.com/gotomicro/ego@v1.1.5/server/egin/interceptor.go:303\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/gotomicro/ego/server/egin.(*Container).defaultServerInterceptor.func1\n\t/go/pkg/mod/github.com/gotomicro/ego@v1.1.5/server/egin/interceptor.go:227\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/RaMin0/gin-health-check.New.func1\n\t/go/pkg/mod/github.com/!ra!min0/gin-health-check@v0.0.0-20180807004848-a677317b3f01/healthcheck.go:61\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:616\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:572\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2916\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1966\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571\ncreate failed 01:\ngithub.com/clickvisual/clickvisual/api/internal/service.StorageCreate\n\t/clickvisual/api/internal/service/table.go:85\ngithub.com/clickvisual/clickvisual/api/internal/api/apiv2/storage.Create\n\t/clickvisual/api/internal/api/apiv2/storage/storage.go:79\ngithub.com/clickvisual/clickvisual/api/pkg/component/core.Handle.func1\n\t/clickvisual/api/pkg/component/core/core.go:23\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/clickvisual/clickvisual/api/internal/middlewares.isNotLogin\n\t/clickvisual/api/internal/middlewares/auth.go:73\ngithub.com/clickvisual/clickvisual/api/internal/middlewares.AuthChecker.func1\n\t/clickvisual/api/internal/middlewares/auth.go:24\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/gin-contrib/sessions.Sessions.func1\n\t/go/pkg/mod/github.com/gin-contrib/sessions@v0.0.5/sessions.go:54\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/gotomicro/ego/server/egin.traceServerInterceptor.func1\n\t/go/pkg/mod/github.com/gotomicro/ego@v1.1.5/server/egin/interceptor.go:331\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/gotomicro/ego/server/egin.metricServerInterceptor.func1\n\t/go/pkg/mod/github.com/gotomicro/ego@v1.1.5/server/egin/interceptor.go:303\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/gotomicro/ego/server/egin.(*Container).defaultServerInterceptor.func1\n\t/go/pkg/mod/github.com/gotomicro/ego@v1.1.5/server/egin/interceptor.go:227\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/RaMin0/gin-health-check.New.func1\n\t/go/pkg/mod/github.com/!ra!min0/gin-health-check@v0.0.0-20180807004848-a677317b3f01/healthcheck.go:61\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:616\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:572\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2916\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1966\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571","tid":"ed45301b486001e0ed063e904b34812b"

后端为单节点clickhouse，截图如下
![image](https://user-images.githubusercontent.com/29787327/223036647-2a179e7e-3f39-4fb8-9409-faffd92c7d50.png)

但是新建日志库却使用了ReplicatedMergeTree，麻烦帮忙看一下问题，谢谢！

**Comment by Chenkeyi43** [comment]
所以这个BUG好像还是没处理啊

**Comment by kl7sn** [comment]
我这边关联下 https://github.com/clickvisual/clickvisual/issues/1006
