### ISSUE TITLE
[FEATURE]:希望可以像kibana那样展示日志时候：显示表头，各个字段以及调整字段顺序

### ISSUE THREAD

**Issue by starsliao** [clickvisual/clickvisual#944]
希望可以像kibana那样折叠展示日志时候：可以显示表头，各个字段以及调整字段顺序。
比如点击折叠日志后，可以显示出表头，一行显示各个字段（隐藏的字段不显示），能支持调整顺序；
点击展开一条日志的时候，显示所有的字段（隐藏了的，展开后也显示。）

**Comment by kl7sn** [comment]
![image](https://user-images.githubusercontent.com/2037801/228417372-890d09e5-50e6-4f03-9f3c-3951e07f1f47.png)
类似这个功能吗，目前 cv 这边只包含了 json 模式

**Comment by starsliao** [comment]
![图片](https://user-images.githubusercontent.com/3349611/229121235-7f480e3d-b7f5-4dc8-800e-85838c5a71a2.png)
我是指这样的展示效果

**Comment by kl7sn** [comment]
这个效果可以切换做在表格模式下，短期内应该没有在日志查询列表增加此类效果的计划。
![image](https://user-images.githubusercontent.com/2037801/229399151-4875ccfc-7cb4-4caf-9884-fb57dea0e55e.png)
