### ISSUE TITLE
[FEATURE]:elk查询结果显示是滚动的，这样就不用做count查询，发现在大数量下做like查询时，用count很慢，如果通过滚动方式显示查询结果，就不需要count语句了

### ISSUE THREAD

**Issue by flylkng** [clickvisual/clickvisual#946]
**Concisely describe the proposed feature**
ELK查询结果显示是滚动的，这样就不用做count查询，发现在大数量下做like查询时，用count很慢，如果通过滚动方式显示查询结果，就不需要count语句了
**Describe the solution you'd like (if any)**
A clear and concise description of what you want to achieve and implement.

**Additional comments**

**Comment by kl7sn** [comment]
感谢提出优化，有些场景还是需要 count 数据，这边会再调研下其他日志平台，逐步提升用户体验。
