### ISSUE TITLE
[BUG]: 修改实例用户名密码的时候报【未知错误，请联系负责人】

### ISSUE THREAD

**Issue by hasylu** [clickvisual/clickvisual#951]
**Describe the bug**
修改实例用户名密码的时候报【未知错误，请联系负责人】
![微信截图_20230323195550](https://user-images.githubusercontent.com/3271307/227199161-0c598248-1979-424b-b2fb-27c34ab60b96.png)

![微信截图_20230323195622](https://user-images.githubusercontent.com/3271307/227199315-330e16a6-fd6c-45ec-8bc9-928b2e8a1259.png)

- ClickVisual version:
- 版本：clickvisual-v0.4.6-rc4-linux-amd64

- ClickVisual.LOG:
没有提示可用日志

**Comment by kl7sn** [comment]
试试这个版本，镜像在编译中 https://github.com/clickvisual/clickvisual/releases/tag/v0.4.6-rc5

**Comment by hasylu** [comment]
好的，回头试用下
