### ISSUE TITLE
切换到SQL查询界面，想导出查询结果，但报没有权限

### ISSUE THREAD

**Issue by w38351479** [clickvisual/clickvisual#953]
![image](https://user-images.githubusercontent.com/20940470/228109810-87863fba-c987-4587-9dc3-15b0aed24655.png)
授权那里已经授权了（即使给全部权限也不行，试过了）
![image](https://user-images.githubusercontent.com/20940470/228110029-ef13d2aa-defb-45ff-b067-9af784c9c24a.png)

具体信息：
{"data":{"code":1,"msg":"","data":"权限验证未通过 (您当前无操作权限). "}}

**Comment by w38351479** [comment]
除非授权作用域是“全部”，否则就算你选了对应数据库和日志库也是不行的

**Comment by hedongfang** [comment]
你实例里面授权了吗？
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/49864372/228157985-a08d9283-8cf8-40ee-b946-e5c2bc41b295.png">
如果授权表，你SQL查询界面就没有库的权限。好像必须授权库

**Comment by w38351479** [comment]
授权了，但也是不行的，只有作用域选“全部”才行
![image](https://user-images.githubusercontent.com/20940470/228165952-2e16037f-4f17-4523-afbc-5dc71a5172f6.png)

**Comment by hedongfang** [comment]
嗯，刚测试了一下，是的。作用域要全部。“全部”风险太大了，使用clickhouse管理员账号可以在SQL查询界面执行drop table 表

**Comment by hedongfang** [comment]
clickhouse给只读权限，又操作不了告警规则。现在只能放弃了SQL界面查询。

**Comment by w38351479** [comment]
不能导出的话，这个影响还是比较大的。考虑修复这个bug不

**Comment by kl7sn** [comment]
因为这里没有限制具体的SQL内容，具备写的功能，所以限制的权限较高
如果要优化，需要在这里限定只执行读SQL

**Comment by w38351479** [comment]
可以的，目前clickvisual大部分人应该都只是用来日志展示和监控告警，查询导出这部分只读足够了

**Comment by kl7sn** [comment]
> 可以的，目前clickvisual大部分人应该都只是用来日志展示和监控告警，查询导出这部分只读足够了

这边尽快优化下，感谢提出意见

**Comment by kl7sn** [comment]
后续开发进度跟踪 #975
