### ISSUE TITLE
fix: the log field area is displayed abnormally

### ISSUE THREAD

**Issue by Cerberuxx** [clickvisual/clickvisual#956]
日志字段在左侧分析字段中没有，重新导入日志库也没用
字段为t1k_detect_time
![image](https://user-images.githubusercontent.com/29787327/231036069-f79237dc-2d52-4dbe-8129-bddeaa80fcaa.png)

**Comment by qianque7** [comment]
打开控制台，查看analysis-fields接口返回的数据里是否有 t1k_detect_time 这一项
