### ISSUE TITLE
选择下一页后，显示未查询到数据(数据库中其实存储数据)

### ISSUE THREAD

**Issue by sixiaojie** [clickvisual/clickvisual#959]
选择图标后，时间范围变成了: 15分钟NaN
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/17584567/231976257-39b21d88-3f5b-410c-aebd-1229474b1f72.png">
选择下一页后，就会变成
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/17584567/231976414-90da4eba-5932-44b6-a753-6085a248223d.png">

**Comment by qianque7** [comment]
https://github.com/clickvisual/clickvisual/pull/960/commits/65a1b5fd9221f444b56234c0a7fe40ffa33eb5e7
