### ISSUE TITLE
[BUG]: 告警配置-- 页面没有配置prometheus文件路径的地方，导致规则一直在配置中

### ISSUE THREAD

**Issue by dengpei89** [clickvisual/clickvisual#967]
0.4.5和0.4.6都没有设置prometheus路径的选项了（没有配置管理），导致新增的规则一直在配置中，后台也没有任务报错（之前有遇到过因为文件权限问题没有创建成功，这次什么都没提示）。

现在clickvisual默认生成的规则文件默认放在那里呢？  页面没有可配置的地方

**Comment by kl7sn** [comment]
报警->环境监测
![image](https://user-images.githubusercontent.com/2037801/232984923-9b419cb2-6edf-4134-93fc-caedf9628789.png)

**Comment by dengpei89** [comment]
v1.0.0-rc1版本，报警下没有环境监测，只有报警列表和通知渠道

**Comment by kl7sn** [comment]
> v1.0.0-rc1版本，报警下没有环境监测，只有报警列表和通知渠道

确认下服务启动加载的 resource.yaml 内容是否与下方文件内容一致
https://github.com/clickvisual/clickvisual/blob/master/config/resource.yaml
