### ISSUE TITLE
[BUG]:接入已有的日志库，无法删除

### ISSUE THREAD

**Issue by FengZh61** [clickvisual/clickvisual#968]
- ClickVisual version:
v1.0.0-rc1

这个库是我自己已有的库，添加完表后，删除表正常，在删除库报错，如果直接删除库，提示需要删除表后再删除库，在实例管理里面，也无法删除实例，提示需要删除库。

![image](https://user-images.githubusercontent.com/98309003/232675511-7c653092-7bae-416d-8635-426ce176dc4f.png)

![image](https://user-images.githubusercontent.com/98309003/232675485-c4445974-0ae5-4d6d-9513-617b49c7b14f.png)

在实例里，添加数据库，接入已有数据库，报错如下：

![image](https://user-images.githubusercontent.com/98309003/232675949-886f5210-9520-42a1-bcad-674a9a1f9b18.png)

新增的日志字段是啥功能啊，接入已有的日志库是不是不支持？

![image](https://user-images.githubusercontent.com/98309003/232676022-3e7883e0-8cba-46d1-97f0-db3837670064.png)

**Comment by kl7sn** [comment]
前两个问题关联到了 https://github.com/clickvisual/clickvisual/issues/971 和 https://github.com/clickvisual/clickvisual/issues/972 

接入已有日志库不支持日志字段配置
