### ISSUE TITLE
[QUESTION]:按教程走完快速上手后未采集日志

### ISSUE THREAD

**Issue by zzw6776** [clickvisual/clickvisual#969]
版本:[v1.0.0-rc1]

日志文件已经在kafka中,我的想法是接入clickvisual,给他一个新的消费组,他应该就能消费
但是实际没有消费kafka,日志里也没报错也没提示

brokers如下
![image](https://user-images.githubusercontent.com/14048998/232684112-80747fff-ad9f-4ba6-968c-76a512043d9b.png)
,
kafka里面是有日志内容的
![image](https://user-images.githubusercontent.com/14048998/232684340-bd735248-8f64-4283-b76e-409992646c73.png)

`{"dateTime":"2023-04-18 13:56:35.002","dtTime":1681797395002,"logLevel":"INFO","method":"balanceWarning(XxlScheduler.java:97)","appNameWithEnv":"pay-_-prod","appName":"pay","serverName":"10.233.105.147","className":"xxxx","env":"prod","content":"余额预警重复提醒:111","seq":289848,"threadName":"Thread-56"}`

clickvisual接入后设置如下
![image](https://user-images.githubusercontent.com/14048998/232685322-5eeaefb2-388f-43d4-b814-360e85260742.png)

![image](https://user-images.githubusercontent.com/14048998/232685439-f62e6d0d-15b6-4b48-876d-e21696e59bb8.png)

**Comment by dengpei89** [comment]
kafka的消息消费后，数据是存在clickhouse吧 ？

**Comment by zzw6776** [comment]
> 

是的,搭了个单机的clickhouse集群,clickhouse也的确建表了
![image](https://user-images.githubusercontent.com/14048998/232687534-450a459e-273e-4a65-a0ef-06687581a968.png)
![image](https://user-images.githubusercontent.com/14048998/232687639-0202afb3-4a5d-4794-a312-59acbcbbbee1.png)
![image](https://user-images.githubusercontent.com/14048998/232687717-dc2ac35d-117b-409f-81b2-052e824c1562.png)

**Comment by dengpei89** [comment]
看看clickhouse有数据吗，再看看clickhouse-server.log日志有没有报错

**Comment by zzw6776** [comment]
> 看看clickhouse有数据吗，再看看clickhouse-server.log日志有没有报错
clickhouse报错了,
![image](https://user-images.githubusercontent.com/14048998/232692824-cddfb31f-ad6d-452d-9735-ec88805204b2.png)
![image](https://user-images.githubusercontent.com/14048998/232693176-bcbadf30-be4e-4bb0-87ba-bf1358a9457b.png)

**Comment by dengpei89** [comment]
F12抓一下clickvisual查询的包，看看起止时间参数是多少，然后直接去clickhouse查询一下看看有没有数据

**Comment by zzw6776** [comment]
我知道了 这个时间有问题,你们用的应该是s解析,我的数据是毫秒  这个有办法处理吗
![image](https://user-images.githubusercontent.com/14048998/232701032-3157bc70-ad46-48b2-b884-e506e7c80f18.png)

**Comment by zzw6776** [comment]
手动重新创建了下view  可以用了  但是希望在添加的时候给个毫秒/秒的选项!
![image](https://user-images.githubusercontent.com/14048998/232705223-e336eb5d-a40d-49b2-8f87-ae254e2a5b9a.png)

**Comment by kl7sn** [comment]
相关优化已关联到 https://github.com/clickvisual/clickvisual/issues/970 并列入开发计划
