### ISSUE TITLE
[QUESTION]: kafka 有数据但是 clickvisual 中没数据 查看 clickhouse 日志报错提示

### ISSUE THREAD

**Issue by manbu1996** [clickvisual/clickvisual#985]
Cannot print extra info for Poco::Exception (version 23.3.2.37 (official build))
2023.05.06 08:54:34.532298 [ 211 ] {} <Error> void DB::StorageKafka::threadFunc(size_t): std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in rename: Permission denied ["/var/lib/clickhouse/store/7f6/7f6c73e0-7df1-465b-bba5-008c151c233f/tmp_insert_20230506_18_18_0/"] ["/var/lib/clickhouse/store/7f6/7f6c73e0-7df1-465b-bba5-008c151c233f/20230506_18_18_0/"], Stack trace (when copying this message, always include the lines below):

0. std::system_error::system_error(std::error_code, String const&) @ 0x1a51b152 in /usr/bin/clickhouse
1. ? @ 0x1a4c0ac4 in /usr/bin/clickhouse
2. ? @ 0x1a4c089d in /usr/bin/clickhouse
3. ? @ 0x1a4c2ef0 in /usr/bin/clickhouse
4. std::__fs::filesystem::__rename(std::__fs::filesystem::path const&, std::__fs::filesystem::path const&, std::error_code*) @ 0x1a4c77dd in /usr/bin/clickhouse
5. DB::DiskLocal::moveDirectory(String const&, String const&) @ 0x12bd7d0b in /usr/bin/clickhouse
6. DB::DataPartStorageOnDiskBase::rename(String, String, Poco::Logger*, bool, bool) @ 0x1446c705 in /usr/bin/clickhouse
7. DB::IMergeTreeDataPart::renameTo(String const&, bool) @ 0x1449a18c in /usr/bin/clickhouse
8. DB::MergeTreeData::preparePartForCommit(std::shared_ptr<DB::IMergeTreeDataPart>&, DB::MergeTreeData::Transaction&, bool) @ 0x14536cce in /usr/bin/clickhouse
9. DB::MergeTreeData::renameTempPartAndReplaceImpl(std::shared_ptr<DB::IMergeTreeDataPart>&, DB::MergeTreeData::Transaction&, std::unique_lock<std::mutex>&, std::vector<std::shared_ptr<DB::IMergeTreeDataPart const>, std::allocator<std::shared_ptr<DB::IMergeTreeDataPart const>>>*) @ 0x1453879b in /usr/bin/clickhouse
10. DB::MergeTreeData::renameTempPartAndAdd(std::shared_ptr<DB::IMergeTreeDataPart>&, DB::MergeTreeData::Transaction&, std::unique_lock<std::mutex>&) @ 0x14538f65 in /usr/bin/clickhouse
11. DB::MergeTreeSink::finishDelayedChunk() @ 0x14876a40 in /usr/bin/clickhouse
12. ? @ 0x14c12ed9 in /usr/bin/clickhouse
13. DB::ExceptionKeepingTransform::work() @ 0x14c128cb in /usr/bin/clickhouse
14. DB::ExecutionThreadContext::executeTask() @ 0x14a2e70a in /usr/bin/clickhouse
15. DB::PipelineExecutor::executeStepImpl(unsigned long, std::atomic<bool>*) @ 0x14a2377b in /usr/bin/clickhouse
16. DB::PipelineExecutor::executeImpl(unsigned long) @ 0x14a228d1 in /usr/bin/clickhouse
17. DB::PipelineExecutor::execute(unsigned long) @ 0x14a22571 in /usr/bin/clickhouse
18. DB::CompletedPipelineExecutor::execute() @ 0x14a20add in /usr/bin/clickhouse
19. DB::StorageKafka::streamToViews() @ 0x14257124 in /usr/bin/clickhouse
20. DB::StorageKafka::threadFunc(unsigned long) @ 0x14255135 in /usr/bin/clickhouse
21. DB::BackgroundSchedulePoolTaskInfo::execute() @ 0x127c0686 in /usr/bin/clickhouse
22. DB::BackgroundSchedulePool::threadFunction() @ 0x127c356a in /usr/bin/clickhouse
23. ? @ 0x127c43ae in /usr/bin/clickhouse
24. ThreadPoolImpl<std::thread>::worker(std::__list_iterator<std::thread, void*>) @ 0xe2b13f3 in /usr/bin/clickhouse
25. ? @ 0xe2b7061 in /usr/bin/clickhouse
26. ? @ 0x7fe264ed6b43 in ?
27. clone @ 0x7fe264f67bb4 in ?

**Comment by kl7sn** [comment]
可以使用 [JSONAsString](https://clickhouse.com/docs/zh/interfaces/formats#jsonasstring) 方式创建一下两个表，保证流程正常
- Kafka Engine Table 
- MergeTree Table

**Comment by manbu1996** [comment]
辛苦问下 我们现在要进行如下的变更 1 利用fluent-bit 将采集到的日志 进行过滤 将日志中的用户信息 脱敏 例如 admin 替换为 ***** 那是否只需要更改下 clickvisual\data\all-in-one\fluent-bit\conf 下面的配置文件即可 那 我看了下
https://clickvisual.gocn.vip/clickvisual/07collect/fluent-bit-configuration-reference.html#_2-2-parse-conf-%E9%85%8D%E7%BD%AE
这个文档 好像并没有讲解下 这里应该怎么书写 和修改

**Comment by kl7sn** [comment]
> 辛苦问下 我们现在要进行如下的变更 1 利用fluent-bit 将采集到的日志 进行过滤 将日志中的用户信息 脱敏 例如 admin 替换为 ***** 那是否只需要更改下 clickvisual\data\all-in-one\fluent-bit\conf 下面的配置文件即可 那 我看了下 https://clickvisual.gocn.vip/clickvisual/07collect/fluent-bit-configuration-reference.html#_2-2-parse-conf-%E9%85%8D%E7%BD%AE 这个文档 好像并没有讲解下 这里应该怎么书写 和修改

fluent-bit 相关文档仅供参考，也可以使用其他采集工具。涉及上面提到具体的功能可以查询 fluent-bit 官方文档进行操作。
