### ISSUE TITLE
[BUG]:clickhouse 实例配置页不可配置为集群

### ISSUE THREAD

**Issue by tianjindaxue1202** [clickvisual/clickvisual#987]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.

**ClickVisual Running Environment**
Please provide the following information:

![image](https://github.com/clickvisual/clickvisual/assets/12711247/1973c0ab-2cfb-40aa-914a-bbf86b73dd62)

- ClickVisual version:
clickvisual version is 1.0
- ClickVisual.LOG:

**Comment by kl7sn** [comment]
点击确认后会识别是否为集群

**Comment by tianjindaxue1202** [comment]
并不会有有效果。
别外请问一下。“分析”那块的作用是什么，在文档里并没有具体的介绍

**Comment by kl7sn** [comment]
并不会有有效果的意思是识别错误吗？帮忙提供下以下数据，感谢
1. SELECT * from system.clusters 的执行结果
2. clickvisual 的识别结果

分析部分是做数据处理的相关功能

**Comment by donglihe** [comment]
执行了 SELECT * from system.clusters ，
![image](https://github.com/clickvisual/clickvisual/assets/23648607/9fc7339b-693e-44e3-9cc2-e5d9eb18900a)
然而显示为
<img width="1403" alt="image" src="https://github.com/clickvisual/clickvisual/assets/23648607/c9540a2b-e22d-4348-b8f2-8dc18c4135a3">

**Comment by donglihe** [comment]
> 

1

**Comment by kl7sn** [comment]
可以更新下最新的 rc 版本，这个地方做了修复。
