### ISSUE TITLE
[BUG]: 分布表告警保存异常

### ISSUE THREAD

**Issue by bourneye** [clickvisual/clickvisual#988]
**Describe the bug**
报警监控规则，点击保存出现表不存在错误
**ClickVisual Running Environment**
kubernetes && clickhouse
CREATE TABLE nginx.access_all
(
    ...
)
ENGINE = Distributed('logs', 'nginx', 'access', rand())
SETTINGS fsync_after_insert = 0, max_delay_to_insert = 60
COMMENT '访问日志分布表'
断点信息如下：
<img width="1180" alt="image" src="https://github.com/clickvisual/clickvisual/assets/17796550/f8477d67-e3fa-4ef1-b0b6-6cfed13fba59">

- ClickVisual version:
1.0.0-rc1
- ClickVisual.LOG:
{"data":{"code":1,"msg":"sql: CREATE MATERIALIZED VIEW IF NOT EXISTS nginx.access_all_b5d63be1_696c_4a4f_b8d1_333e9598f285_10 on cluster 'logs' TO metrics.samples AS\nSELECT\n  toDate(time_iso8601) as date,\n  'clickvisual_alert_metrics' as name,\n  array('uuid=b5d63be1-696c-4a4f-b8d1-333e9598f285','alarmId=1','filterId=10') as tags,\n  toFloat64(count(*)) as val,\n  time_iso8601 as ts,\n  toDateTime(time_iso8601) as updated\nFROM `nginx`.`access, rand())\nSETTINGS fsync_after_insert = 0`\nWHERE 1=1 GROUP BY time_iso8601;: code: 60, message: Table nginx.`access, rand())\\nSETTINGS fsync_after_insert = 0` doesn't exist","data":"sql: CREATE MATERIALIZED VIEW IF NOT EXISTS nginx.access_all_b5d63be1_696c_4a4f_b8d1_333e9598f285_10 on cluster 'logs' TO metrics.samples AS\nSELECT\n  toDate(time_iso8601) as date,\n  'clickvisual_alert_metrics' as name,\n  array('uuid=b5d63be1-696c-4a4f-b8d1-333e9598f285','alarmId=1','filterId=10') as tags,\n  toFloat64(count(*)) as val,\n  time_iso8601 as ts,\n  toDateTime(time_iso8601) as updated\nFROM `nginx`.`access, rand())\nSETTINGS fsync_after_insert = 0`\nWHERE 1=1 GROUP BY time_iso8601;: code: 60, message: Table nginx.`access, rand())\\nSETTINGS fsync_after_insert = 0` doesn't exist"}}

**Comment by kl7sn** [comment]
可以直接在 clickhouse 执行 sql 看下

确认涉及的表是否都存在
- nginx.access
- metrics.samples
