### ISSUE TITLE
前端页面似乎强制分为“基础字段”和“日志字段”

### ISSUE THREAD

**Issue by w38351479** [clickvisual/clickvisual#992]
clickvisual-v0.4.6后的版本，强制分为“基础字段”和“日志字段”两种，问题是接入已有日志库时，并不能指定哪些是“”日志字段”，全部都属于“基础字段”啊，等于页面字段选择处有一半不能用，并不能自动调节位置。这样是否合理？

**Comment by kl7sn** [comment]
已接入日志库的现有字段都归属于基础字段，新增的分析字段为日志字段。

**Comment by w38351479** [comment]
前端能否修复只有一半可用的问题
![image](https://github.com/clickvisual/clickvisual/assets/20940470/20763beb-7535-47b6-b351-7f1ba01bff43)

**Comment by kl7sn** [comment]
> 前端能否修复只有一半可用的问题 ![image](https://user-images.githubusercontent.com/20940470/238231499-20763beb-7535-47b6-b351-7f1ba01bff43.png)

尽快优化，感谢反馈。

**Comment by w38351479** [comment]
clickvisual-v1.0.0-rc2 该版本修复放大问题后，右侧进度条消失，无法查看列表下面的选项
